/*
 * pnl_Generico.java
 *
 * Created on 05 de noviembre de 2008, 06:04 PM
 */

package contac.servicio.app.panel;



import contac.commons.form.panel.GenericFrame;

/**
 *
 * @author  KjSoftware
 */
public abstract class pnl_Generico extends javax.swing.JPanel {
    
    public GenericFrame frame;
   
    //key: LLAVE CON QUE IDENTIFICAMOS AL PANEL
    private String key = "MOD-01";
    //NOMBRE DEL MODULO QUE APARECERA EN LA PESTAÑA
    private String tituloModulo = "";
    //NOMBRE DESCRITO DEL MODULO QUE SE MOSTRARA EN LA PESTAÑA
    private String toolTip = "";
    /** Creates new form pnl_Generico */
    
    private boolean cierrePermitido = true;
    
    public pnl_Generico() {
        
    }
    
    // <editor-fold defaultstate="collapsed" desc="METODOS SETTER & GETTER">
    
    public void setMDI(GenericFrame mdi){
        this.frame = mdi;
    }
    public boolean validarCierre(){
        this.cleanMemory();
        return this.cierrePermitido;
    }
    public GenericFrame getMDI(){
        return this.frame;
    }
    public void setTitulo(String titulo){
        this.tituloModulo = titulo;
    }
    public String getTitulo(){
        return this.tituloModulo;
    }
    public void setPanelTip(String tooltip){
        this.toolTip = tooltip;
    }
    public String getPanelTip(){
        return this.toolTip;
    }
    public void setKey(String key){
        this.key = key;
    }
    public String getKey(){
        return this.key;
    }
    private void cleanMemory(){
        System.gc();
    }
    // </editor-fold>
     

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 356, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 252, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
