/**
 * Copyright 2012 Contac Business Software. All rights reserved.
 * CONTAC PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */

/*
 * pnlMonedas.java
 *
 * Created on 02-11-2012, 11:27:29 PM
 */
package contac.administracion.moneda.app;

import contac.administracion.controller.MonedaController;
import contac.commons.form.label.JOptionErrorPane;
import contac.commons.form.panel.GenericFrame;
import contac.commons.form.panel.GenericPanel;
import contac.commons.models.tables.BeanTableModel;
import contac.internationalization.LanguageLocale;
import contac.modelo.entity.Moneda;
import org.apache.log4j.Logger;

import javax.swing.*;
import javax.swing.table.TableColumnModel;
import java.util.Locale;
import java.util.ResourceBundle;

/**
 * @author EMontenegro
 */
public class pnlMonedas extends GenericPanel {

    //Logger
    private static final Logger logger = Logger.getLogger(pnlTiposCambio.class);

    //Message Resource Bundle
    private ResourceBundle messageBundle = ResourceBundle.getBundle("contac/administracion/app/mensajes/Mensajes",
            LanguageLocale.getInstance().getLocale());

    //Controller
    private MonedaController controller;

    /**
     * Creates new form pnlMonedas
     */
    public pnlMonedas(GenericFrame frame) {

        //Call super constructor
        super(frame, "Monedas", "Monedas", true, "contac/administracion/app/mensajes/Mensajes",
                new Locale("es", "NIC"));

        //Init controller
        controller = new MonedaController();

        //Init registros
        controller.initRegistrosMonedas();

        //Init components
        initComponents();

        //Init values
        initValues();
    }

    @Override
    public void initValues() {

        //Configura table model
        monedaBeanTableModel = new BeanTableModel<Moneda>(Moneda.class, controller.getMonedas());
        monedaBeanTableModel.setModelEditable(false);
        tblMonedas.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblMonedas.setModel(monedaBeanTableModel);
        tblMonedas.setRowSelectionAllowed(true);

        //Obteniendo table column model y removimiento columnas innecesarias
        TableColumnModel columnModel = tblMonedas.getColumnModel();
        String[] columnsRemove = new String[]{"Id", "Pais", "Ctime", "Cuser", "Mtime", "Muser"};

        for (String columnLabel : columnsRemove) {
            columnModel.removeColumn(columnModel.getColumn(columnModel.getColumnIndex(columnLabel)));
        }
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new org.jdesktop.swingx.JXHeader();
        pnlAdmonMonedas = new javax.swing.JPanel();
        scrollCompania = new javax.swing.JScrollPane();
        tblMonedas = new javax.swing.JTable();
        tbAcciones = new javax.swing.JToolBar();
        btnNuevo = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnModificar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnRemover = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnActualizar = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        header.setForeground(new java.awt.Color(255, 153, 0));
        header.setPreferredSize(new java.awt.Dimension(51, 35));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("contac/administracion/app/mensajes/Mensajes_es"); // NOI18N
        header.setTitle(bundle.getString("CONTAC.FORM.MONEDAS.TITLE")); // NOI18N
        header.setTitleForeground(new java.awt.Color(255, 153, 0));
        add(header, java.awt.BorderLayout.NORTH);

        pnlAdmonMonedas.setLayout(new java.awt.BorderLayout());

        scrollCompania.setPreferredSize(new java.awt.Dimension(452, 420));

        tblMonedas.setMinimumSize(new java.awt.Dimension(60, 90));
        tblMonedas.setPreferredSize(new java.awt.Dimension(300, 280));
        tblMonedas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMonedasMouseClicked(evt);
            }
        });
        scrollCompania.setViewportView(tblMonedas);

        pnlAdmonMonedas.add(scrollCompania, java.awt.BorderLayout.CENTER);

        tbAcciones.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tbAcciones.setMaximumSize(new java.awt.Dimension(124, 32));
        tbAcciones.setMinimumSize(new java.awt.Dimension(124, 32));

        btnNuevo.setIcon(new ImageIcon(getClass().getResource("/contac/resources/icons/actions/new.png")));
        btnNuevo.setToolTipText(bundle.getString("CONTAC.FORM.BTNNUEVO")); // NOI18N
        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNuevo.setEnabled(false);
        btnNuevo.setFocusable(false);
        btnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnNuevo.setMaximumSize(new java.awt.Dimension(40, 32));
        btnNuevo.setMinimumSize(new java.awt.Dimension(40, 32));
        btnNuevo.setPreferredSize(new java.awt.Dimension(40, 32));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        tbAcciones.add(btnNuevo);
        tbAcciones.add(jSeparator1);

        btnModificar.setIcon(new ImageIcon(getClass().getResource("/contac/resources/icons/actions/edit.png")));
        btnModificar.setToolTipText(bundle.getString("CONTAC.FORM.BTNEDITAR")); // NOI18N
        btnModificar.setEnabled(false);
        btnModificar.setFocusable(false);
        btnModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModificar.setMaximumSize(new java.awt.Dimension(40, 32));
        btnModificar.setMinimumSize(new java.awt.Dimension(40, 32));
        btnModificar.setName(""); // NOI18N
        btnModificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        tbAcciones.add(btnModificar);
        tbAcciones.add(jSeparator2);

        btnRemover.setIcon(new ImageIcon(getClass().getResource("/contac/resources/icons/actions/remove.png")));
        btnRemover.setToolTipText(bundle.getString("CONTAC.FORM.BTNREMOVER")); // NOI18N
        btnRemover.setEnabled(false);
        btnRemover.setFocusable(false);
        btnRemover.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnRemover.setMaximumSize(new java.awt.Dimension(40, 32));
        btnRemover.setMinimumSize(new java.awt.Dimension(40, 32));
        btnRemover.setName(""); // NOI18N
        tbAcciones.add(btnRemover);
        tbAcciones.add(jSeparator3);

        btnActualizar.setIcon(new ImageIcon(getClass().getResource("/contac/resources/icons/actions/reload.png")));
        btnActualizar.setToolTipText(bundle.getString("CONTAC.FORM.BTNACTUALIZAR")); // NOI18N
        btnActualizar.setFocusable(false);
        btnActualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnActualizar.setMaximumSize(new java.awt.Dimension(40, 32));
        btnActualizar.setMinimumSize(new java.awt.Dimension(40, 32));
        btnActualizar.setName(""); // NOI18N
        btnActualizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        tbAcciones.add(btnActualizar);

        pnlAdmonMonedas.add(tbAcciones, java.awt.BorderLayout.PAGE_START);

        add(pnlAdmonMonedas, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tblMonedasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMonedasMouseClicked


    }//GEN-LAST:event_tblMonedasMouseClicked

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed

    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        try {
            //Actualiar registro de monedas
            controller.actualizarRegistroMonedas();

            //Actualizar tblMonedas
            ((BeanTableModel) tblMonedas.getModel()).fireTableDataChanged();

        } catch (Exception e) {
            logger.error(e.getMessage(), e);
            JOptionErrorPane.showMessageError(null, messageBundle.getString("CONTAC.FORM.MSG.ERROR.BUSQUEDA"),
                    e.getMessage());
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRemover;
    private org.jdesktop.swingx.JXHeader header;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JPanel pnlAdmonMonedas;
    private javax.swing.JScrollPane scrollCompania;
    private javax.swing.JToolBar tbAcciones;
    private javax.swing.JTable tblMonedas;
    // End of variables declaration//GEN-END:variables

    private BeanTableModel<Moneda> monedaBeanTableModel;
    private Moneda monedaSelected;
    private int rowSelected;
}
