/**
 * Copyright 2012 Contac Business Software. All rights reserved.
 * CONTAC PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */

/*
 * pnlTiposCambio.java
 *
 * Created on 02-12-2012, 12:01:15 AM
 */
package contac.administracion.moneda.app;

import contac.commons.form.panel.GenericFrame;
import contac.commons.form.panel.GenericPanel;
import contac.internationalization.LanguageLocale;
import org.apache.log4j.Logger;

import javax.swing.*;
import java.util.Locale;
import java.util.ResourceBundle;

/**
 * @author EMontenegro
 */
public class pnlTiposCambio extends GenericPanel {

    //Logger
    private static final Logger logger = Logger.getLogger(pnlTiposCambio.class);

    //Message Resource Bundle
    private ResourceBundle messageBundle = ResourceBundle.getBundle("contac/administracion/app/mensajes/Mensajes",
            LanguageLocale.getInstance().getLocale());

    //Panel access configuration
    private pnlBancos pnlBancos;
    private pnlMonedas pnlMonedas;
    private pnlTasasCambio pnlTasasCambio;

    /**
     * Creates new form pnlTiposCambio
     */
    public pnlTiposCambio(GenericFrame frame) {

        //Call super constructor
        super(frame, "Tipos de Cambio", "Tipos de Cambio", true, "contac/administracion/app/mensajes/Mensajes",
                new Locale("es", "NIC"));

        //Configure panel components
        pnlBancos = new pnlBancos(frame);
        pnlMonedas = new pnlMonedas(frame);
        pnlTasasCambio = new pnlTasasCambio(frame);

        //Init componentes
        initComponents();

        //Init values
        initValues();
    }

    @Override
    public void initValues() {

        //Adding tab panel config
        this.tbTiposCambio.addTab(messageBundle.getString("CONTAC.FORM.MONEDAS.TITLE"), pnlMonedas);
        this.tbTiposCambio.addTab(messageBundle.getString("CONTAC.FORM.BANCOS.TITLE"), pnlBancos);
        this.tbTiposCambio.addTab(messageBundle.getString("CONTAC.FORM.TASASCAMBIO.TITLE"), pnlTasasCambio);

        this.tbTiposCambio.setTabPlacement(JTabbedPane.BOTTOM);
        this.tbTiposCambio.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbTiposCambio = new javax.swing.JTabbedPane();

        setLayout(new java.awt.BorderLayout());

        tbTiposCambio.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        add(tbTiposCambio, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tbTiposCambio;
    // End of variables declaration//GEN-END:variables
}
