-- REGISTRAR ESTADOS MOVIMIENTOS
INSERT INTO INV_ESTADO_MOVIMIENTO(N_ID, C_NOMBRE, C_DESCRIPCION, C_ALIAS, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(1, 'INGRESADO', 'INGRESADO', 'IN', 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_ESTADO_MOVIMIENTO(N_ID, C_NOMBRE, C_DESCRIPCION, C_ALIAS, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(2, 'ANULADO', 'ANULADO', 'AN', 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_ESTADO_MOVIMIENTO(N_ID, C_NOMBRE, C_DESCRIPCION, C_ALIAS, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(3, 'PENDIENTE', 'PENDIENTE', 'PD', 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_ESTADO_MOVIMIENTO(N_ID, C_NOMBRE, C_DESCRIPCION, C_ALIAS, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(4, 'PROCESADO', 'PROCESADO', 'PC', 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_ESTADO_MOVIMIENTO(N_ID, C_NOMBRE, C_DESCRIPCION, C_ALIAS, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(5, 'APLICADO', 'APLICADO', 'AP', 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_ESTADO_MOVIMIENTO(N_ID, C_NOMBRE, C_DESCRIPCION, C_ALIAS, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(6, 'CALCULADO', 'CALCULADO', 'CA', 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_ESTADO_MOVIMIENTO(N_ID, C_NOMBRE, C_DESCRIPCION, C_ALIAS, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(7, 'PAGADO', 'PAGADO', 'PG', 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_ESTADO_MOVIMIENTO(N_ID, C_NOMBRE, C_DESCRIPCION, C_ALIAS, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(8, 'IMPRESO', 'IMPRESO', 'IM', 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());

-- REGISTRAR TIPOS DE PAGO
INSERT INTO FAC_TIPO_PAGO(N_ID, C_NOMBRE, C_DESCRIPCION, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(1, 'EFECTIVO', 'EFECTIVO', 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO FAC_TIPO_PAGO(N_ID, C_NOMBRE, C_DESCRIPCION, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(2, 'TARJETA', 'TARJETA', 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO FAC_TIPO_PAGO(N_ID, C_NOMBRE, C_DESCRIPCION, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(3, 'CHEQUE', 'CHEQUE', 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO FAC_TIPO_PAGO(N_ID, C_NOMBRE, C_DESCRIPCION, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(4, 'MIXTO', 'MIXTO', 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());