--REGISTRAR UNSPCS-SPANISH NACIONES UNIDAS

--SEGMENTO
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105591, 48000000, 105591, 'MAQUINARIA, EQUIPO Y SUMINISTROS PARA LA INDUSTRIA DE SERVICIOS', 105591, 0, NULL, NULL, 1, 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME) 
VALUES(105688, 49000000, 105688, 'EQUIPOS, SUMINISTROS Y ACCESORIOS DEPORTIVOS Y RECREATIVOS', 105688, 0, NULL, NULL, 1, 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());

--FAMILIA
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME) 
VALUES(111508, 48120000, 111508, 'EQUIPO DE JUEGO O DE APOSTAR', 111508, 0, NULL, 105591, 2, 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME) 
VALUES(105747, 49120000, 105747, 'EQUIPOS Y ACCESORIOS PARA ACAMPADA Y EXTERIOR', 105747, 0, NULL, 105688, 2, 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME) 
VALUES(105762, 49130000, 105762, 'EQUIPOS DE PESCA Y CAZA', 105762, 0, NULL, 105688, 2, 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME) 
VALUES(105777, 49140000, 105777, 'EQUIPOS PARA DEPORTES ACUATICOS', 105777, 0, NULL, 105688, 2, 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME) 
VALUES(105794, 49150000, 105794, 'EQUIPOS PARA DEPORTES DE INVIERNO', 105794, 0, NULL, 105688, 2, 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME) 
VALUES(105805, 49160000, 105805, 'EQUIPOS DEPORTIVOS PARA CAMPOS Y CANCHAS', 105805, 0, NULL, 105688, 2, 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME) 
VALUES(105836, 49170000, 105836, 'EQUIPOS DE GIMNASIA Y BOXEO', 105836, 0, NULL, 105688, 2, 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME) 
VALUES(105846, 49180000, 105846, 'JUEGOS Y EQUIPO DE TIRO Y MESA', 105846, 0, NULL, 105688, 2, 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME) 
VALUES(105863, 49200000, 105863, 'EQUIPOS PARA ENTRENAMIENTO FISICO', 105863, 0, NULL, 105688, 2, 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME) 
VALUES(105878, 49210000, 105878, 'OTROS DEPORTES', 105878, 0, NULL, 105688, 2, 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME) 
VALUES(105885, 49220000, 105885, 'EQUIPO DE DEPORTE Y ACCESORIOS', 105885, 0, NULL, 105688, 2, 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME) 
VALUES(105914, 49240000, 105914, 'EQUIPO DE RECREO Y PARQUES INFANTILES Y EQUIPO DE SUMINISTROS DE NATACION Y DE SPA', 105914, 0, NULL, 105688, 2, 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());



--CLASE
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME) 
VALUES(111509, 48121100, 107784, 'MAQUINAS DE JUEGO OPERADO CON MONEDAS', 107784, 0, NULL, 111508, 3, 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME) 
VALUES(111511, 48121200, 111509, 'MESAS DE JUEGO Y JUEGOS', 111509, 0, NULL, 111508, 3, 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME) 
VALUES(111514, 48121300, 111511, 'GESTION DE JUEGO Y SISTEMAS DE APOSTAR A RED', 111511, 0, NULL, 111508, 3, 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME) 
VALUES(105748, 49121500, 105748, 'EQUIPOS PARA ACAMPADA Y EXTERIOR', 105748, 0, NULL, 105747, 3, 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME) 
VALUES(105758, 49121600, 105758, 'MUEBLES DE CAMPING', 105758, 0, NULL, 105747, 3,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105763, 49131500, 105763, 'APAREJOS DE PESCA', 105770, 0, NULL, 105762, 3,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105770, 49131600, 105770, 'PRODUCTOS DE CAZA', 105770, 0, NULL, 105762, 3,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105778, 49141500, 105777, 'ESCAFANDRAS AUTONOMAS Y TUBOS DE RESPIRACION', 105777, 0, NULL, 105777, 3,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105786, 49141600, 105786, 'EQUIPOS Y ACCESORIOS PARA WINDSURF Y NATACION', 105786, 0, NULL, 105777, 3,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105806, 49161500, 105806, 'EQUIPOS PARA DEPORTES DE CAMPO', 105806, 0, NULL, 105805, 3,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105817, 49161600, 105817, 'EQUIPOS PARA DEPORTES DE RAQUETA Y PISTA', 105817, 0, NULL, 105805, 3,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105828, 49161700, 105828, 'EQUIPOS PARA DEPORTES DE PISTA', 105828, 0, NULL, 105805, 3,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105837, 49171500, 105837, 'EQUIPOS DE GIMNASIA', 105837, 0, NULL, 105836, 3,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105842, 49171600, 105842, 'EQUIPOS DE BOXEO', 105842, 0, NULL, 105836, 3,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105847, 49181500, 105847, 'EQUIPOS Y JUEGOS DE MESA', 105847, 0, NULL, 105846, 3,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105855, 49181600, 105855, 'EQUIPOS Y JUEGOS DE TIRO AL BLANCO', 105855, 0, NULL, 105846, 3,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105864, 49201500, 105864, 'EQUIPO DE ENTRENAMIENTO PARA AEROBIC', 105864, 0, NULL, 105863, 3,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());


--ARTICULO
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME) 
VALUES(107784, 48121101, 107784, 'MAQUINAS DE JUEGO OPERADO CON MONEDAS', 107784, 0, NULL, 107784, 4, 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME) 
VALUES(105750, 49121502, 105750, 'COLCHONES DE ESPUMA', 105750, 0, NULL, 105748, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME) 
VALUES(105751, 49121503, 105751, 'TIENDAS DE CAMPAÑA', 105751, 0, NULL, 105748, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME) 
VALUES(105752, 49121504, 105752, 'SACOS DE DORMIR', 105752, 0, NULL, 105748, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME) 
VALUES(105753, 49121505, 105753, 'NEVERAS PORTATILES', 105753, 0, NULL, 105748, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME) 
VALUES(105754, 49121506, 105754, 'JUEGOS PARA REPARAR TIENDAS DE CAMPAÑA', 105754, 0, NULL, 105748, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME) 
VALUES(105755, 49121507, 105755, 'COLCHONES DE AIRE', 105755, 0, NULL, 105748, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME) 
VALUES(105756, 49121508, 105756, 'MOSQUITERAS', 105756, 0, NULL, 105748, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME) 
VALUES(105757, 49121509, 105757, 'CAMPING GAS', 105757, 0, NULL, 105748, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME) 
VALUES(132964, 49121510, 132964, 'REFRIGERADORES PARA BEBIDAS', 132964, 0, NULL, 105748, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME) 
VALUES(105759, 49121601, 105759, 'SILLAS O TABURETES DE CAMPING', 105759, 0, NULL, 105758, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105760, 49121602, 105760, 'MESAS DE CAMPING', 105760, 0, NULL, 105758, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105761, 49121603, 105761, 'CATRES DESMONTABLES DE CAMPING', 105761, 0, NULL, 105758, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105764, 49131501, 105764, 'CAÑAS DE PESCA', 105764, 0, NULL, 105763, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105765, 49131502, 105765, 'SEDAL DE PESCA', 105765, 0, NULL, 105763, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105766, 49131503, 105766, 'CARRETES PARA SEDAL DE PESCA', 105766, 0, NULL, 105763, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105767, 49131504, 105767, 'SEÑUELOS PARA PESCA', 105767, 0, NULL, 105763, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105768, 49131505, 105768, 'CEBOS PARA PESCA', 105768, 0, NULL, 105763, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105769, 49131506, 105769, 'PESOS O PLOMOS DE PESCA', 105769, 0, NULL, 105763, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105771, 49131601, 105771, 'RECLAMOS PARA ANIMALES', 105771, 0, NULL, 105770, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105772, 49131602, 105772, 'SEÑUELOS DEPORTIVOS', 105772, 0, NULL, 105770, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105773, 49131603, 105773, 'TRAMPAS DEPORTIVAS', 105773, 0, NULL, 105770, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105774, 49131604, 105774, 'ARMAS DEPORTIVAS', 105774, 0, NULL, 105770, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105775, 49131605, 105775, 'ESCOPETAS DEPORTIVAS', 105775, 0, NULL, 105770, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105776, 49131606, 105776, 'MUNICIONES DEPORTIVAS', 105776, 0, NULL, 105770, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(132972, 49131607, 132972, 'CAÑONES PARA ARMAS', 132972, 0, NULL, 105770, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105779, 49141501, 105779, 'COMPENSADORES DE FLOTACION', 105779, 0, NULL, 105778, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105780, 49141502, 105780, 'TANQUES DE AIRE COMPRIMIDO PARA BUCEO', 105780, 0, NULL, 105778, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105781, 49141503, 105781, 'REGULADORES PARA ESCAFANDRAS AUTONOMAS', 105781, 0, NULL, 105778, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105782, 49141504, 105782, 'INSTRUMENTOS O ACCESORIOS PARA BUCEO', 105782, 0, NULL, 105778, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105783, 49141505, 105783, 'MASCARAS, ALETAS O TUBOS', 105783, 0, NULL, 105778, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105784, 49141506, 105784, 'TRAJES ISOTERMICOS', 105784, 0, NULL, 105778, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105785, 49141507, 105785, 'TRAJES PARA NATACION SUBMARINA', 105785, 0, NULL, 105778, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105788, 49141602, 105788, 'TABLAS DE WAKE, KNEE Y BOOGIE', 105788, 0, NULL, 105786, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105789, 49141603, 105789, 'ESQUIS ACUATICOS O ACCESORIOS', 105789, 0, NULL, 105786, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105790, 49141604, 105790, 'EQUIPO DE WINDSURF', 105790, 0, NULL, 105786, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105791, 49141605, 105791, 'TABLAS DE WINDSURF', 105791, 0, NULL, 105786, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105792, 49141606, 105792, 'GAFAS O ALETAS PARA NATACION', 105792, 0, NULL, 105786, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105793, 49141607, 105793, 'EQUIO DE PARAPENTE', 105793, 0, NULL, 105786, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105807, 49161501, 105807, 'GUIAS DE BLOQUEO PARA FUTBOL AMERICANO', 105807, 0, NULL, 105806, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105808, 49161502, 105808, 'GUANTES DE BEISBOL', 105808, 0, NULL, 105806, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105809, 49161503, 105809, 'PELOTAS DE BEISBOL', 105809, 0, NULL, 105806, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105810, 49161504, 105810, 'BALONES DE FUTBOL AMERICANO', 105810, 0, NULL, 105806, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105811, 49161505, 105811, 'BALONES DE FUTBOL', 105811, 0, NULL, 105806, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105812, 49161506, 105812, 'BATES DE BEISBOL', 105812, 0, NULL, 105806, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105813, 49161507, 105813, 'BASES DE BEISBOL', 105813, 0, NULL, 105806, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105814, 49161508, 105814, 'MAQUINAS LANZADORAS DE BEISBOL', 105814, 0, NULL, 105806, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105815, 49161509, 105815, 'PELOTAS DE SOFTBALL', 105815, 0, NULL, 105806, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105816, 49161510, 105816, 'MUÑECOS DE PLACAJE DE FUTBOL AMERICANO', 105816, 0, NULL, 105806, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(132970, 49161511, 132970, 'PALOS DE LACROSSE', 132970, 0, NULL, 105806, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(133695, 49161512, 133695, 'BOLAS DE LACROSSE', 133695, 0, NULL, 105806, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(133696, 49161513, 133696, 'PALOS DE HOCKEY SOBRE HIERBA', 133696, 0, NULL, 105806, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(133697, 49161514, 133697, 'PELOTAS DE HOCKEY SOBRE HIERBA', 133697, 0, NULL, 105806, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(133698, 49161515, 133698, 'BALONES DE BALONMANO DE EQUIPO', 133698, 0, NULL, 105806, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(133699, 49161516, 133699, 'SETS ESCOLARES DE BALONMANO DE EQUIPO', 133699, 0, NULL, 105806, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(133700, 49161517, 133700, 'EQUIPO DE PROTECCION DE BEISBOL O SOFTBALL', 133700, 0, NULL, 105806, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(133701, 49161518, 133701, 'MATERIAL DE BATEO DE BEISBOL', 133701, 0, NULL, 105806, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(133702, 49161519, 133702, 'VALLAS O LIMITACIONES DE CAMPO DE BEISBOL', 133702, 0, NULL, 105806, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(133703, 49161520, 133703, 'BATES DE SOFTBALL', 133703, 0, NULL, 105806, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(133704, 49161521, 133704, 'GUANTES DE SOFTBALL', 133704, 0, NULL, 105806, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(133705, 49161522, 133705, 'SOPORTE PARA BALON PARA PATADAS DE FUTBOL AMERICANO', 133705, 0, NULL, 105806, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(133706, 49161523, 133706, 'BANDERINES DE FUTBOL', 133706, 0, NULL, 105806, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(133707, 49161524, 133707, 'EQUIPO DE MARCADO DE CAMPO DE FUTBOL', 133707, 0, NULL, 105806, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(133708, 49161525, 133708, 'EQUIPO DE PROTECCION DE FUTBOL', 133708, 0, NULL, 105806, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(133709, 49161526, 133709, 'MATERIAL DE ENTRENAMIENTO DE FUTBOL', 133709, 0, NULL, 105806, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105818, 49161601, 105818, 'RAQUETAS DE RAQUETBOL', 105818, 0, NULL, 105817, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105819, 49161602, 105819, 'RAQUETAS DE BADMINTON', 105819, 0, NULL, 105817, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105820, 49161603, 105820, 'PELOTAS DE BALONCESTO', 105820, 0, NULL, 105817, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105821, 49161604, 105821, 'PELOTAS DE TENIS', 105821, 0, NULL, 105817, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105822, 49161605, 105822, 'PELOTAS DE RAQUETBOL', 105822, 0, NULL, 105817, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105823, 49161606, 105823, 'PELOTAS DE SQUASH', 105823, 0, NULL, 105817, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105824, 49161607, 105824, 'RAQUETAS DE TENIS', 105824, 0, NULL, 105817, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105825, 49161608, 105825, 'PELOTAS DE VOLEIBOL', 105825, 0, NULL, 105817, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105826, 49161609, 105826, 'VOLANTES DE BADMINTON', 105826, 0, NULL, 105817, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105827, 49161610, 105827, 'RAQUETAS DE SQUASH', 105827, 0, NULL, 105817, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(133710, 49161611, 133710, 'MATERIAL DE ENTRENAMIENTO DE TENIS', 133710, 0, NULL, 105817, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(133711, 49161612, 133711, 'EQUIPO DE PISTA DE TENIS', 133711, 0, NULL, 133711, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(133712, 49161613, 133712, 'ALMACENAMIENTO DE BALONES O REDES DE VOLEIBOL', 133712, 0, NULL, 105817, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(133713, 49161614, 133713, 'ESTANDAR DE CANCHAS DE VOLEIBOL', 133713, 0, NULL, 105817, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(133714, 49161615, 133714, 'SISTEMAS COMPLETOS DE JUEGO DE BALONCESTO', 133714, 0, NULL, 105817, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(133715, 49161616, 133715, 'EQUIPO DE PROTECCION DE HOCKEY DE PISTA', 133715, 0, NULL, 105817, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(133716, 49161617, 133716, 'POSTES DE CADENA', 133716, 0, NULL, 105817, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(133717, 49161618, 133717, 'PELOTAS DE POSTES DE CADENA', 133717, 0, NULL, 105817, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(137171, 49161619, 137171, 'CUERDAS DE RAQUETA', 137171, 0, NULL, 105817, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(137201, 49161620, 137201, 'EMPUÑADURAS DE RAQUETA', 137201, 0, NULL, 105817, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105829, 49161701, 105829, 'JABALINAS', 105829, 0, NULL, 105828, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105830, 49161702, 105830, 'BARRAS DE SALTO', 105830, 0, NULL, 105828, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105831, 49161703, 105831, 'DISCOS', 105831, 0, NULL, 105828, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105832, 49161704, 105832, 'PESOS', 105832, 0, NULL, 105828, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105833, 49161705, 105833, 'PERTIGAS', 105833, 0, NULL, 105828, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105834, 49161706, 105834, 'VALLAS', 105834, 0, NULL, 105828, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105835, 49161707, 105835, 'TESTIGOS', 105835, 0, NULL, 105828, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105838, 49171501, 105838, 'BARRAS DE EQUILIBRIO PARA GIMNASIA', 105838, 0, NULL, 105837, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105839, 49171502, 105839, 'CUERDAS, ANILLAS O ACCESORIOS GIMNASTICOS PARA TREPAR', 105839, 0, NULL, 105837, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105840, 49171503, 105840, 'EQUIPOS GIMNASTICOS PARA SALTOS', 105840, 0, NULL, 105837, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105841, 49171504, 105841, 'TRAMPOLINES GIMNASTICOS', 105841, 0, NULL, 105837, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(133718, 49171505, 133718, 'EQUIPO DE EQUILIBRIO', 133718, 0, NULL, 105837, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105843, 49171601, 105843, 'RINGS DE BOXEO', 105843, 0, NULL, 105842, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105844, 49171602, 105844, 'BOLSAS DE ARENA', 105844, 0, NULL, 105842, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105845, 49171603, 105845, 'GUANTES DE BOXEO', 105845, 0, NULL, 105842, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105848, 49181501, 105848, 'MESAS DE BILLAR', 105848, 0, NULL, 105847, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105849, 49181502, 105849, 'TACOS DE BILLAR', 105849, 0, NULL, 105847, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105850, 49181503, 105850, 'JUEGO DE TEJO', 105850, 0, NULL, 105847, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105851, 49181504, 105851, 'BILLAR AUTOMATICO', 105851, 0, NULL, 105847, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105852, 49181505, 105852, 'BOLAS DE BILLAR', 105852, 0, NULL, 105847, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105853, 49181506, 105853, 'TABLAS Y ACCESORIOS PARA HOCKEY AEREO', 105853, 0, NULL, 105847, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105854, 49181507, 105854, 'MESAS DE TENIS', 105854, 0, NULL, 105847, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(133719, 49181508, 133719, 'PALAS DE PING-PONG', 133719, 0, NULL, 105847, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(133720, 49181509, 133720, 'PELOTAS DE PING-PONG', 133720, 0, NULL, 105847, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(133721, 49181510, 133721, 'FUTBOLINES', 133721, 0, NULL, 105847, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(133722, 49181511, 133722, 'BOLAS DE FUTBOLIN', 133722, 0, NULL, 105847, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(133723, 49181512, 133723, 'JUGADORES DE SUSTITUCION DE FUTBOLIN', 133723, 0, NULL, 105847, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(133724, 49181513, 133724, 'EXTREMOS DE TACO DE BILLAR', 133724, 0, NULL, 105847, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(133725, 49181514, 133725, 'TIZA PARA TACO DE BILLAR', 133720, 0, NULL, 105847, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(133726, 49181515, 133726, 'PORTATACOS DE BILLAR', 133726, 0, NULL, 105847, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105857, 49181601, 105857, 'BLANCOS DE TIRO AL ARCO', 105857, 0, NULL, 105855, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105858, 49181602, 105858, 'ARCOS DE TIRO AL ARCO', 105858, 0, NULL, 105855, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105859, 49181603, 105859, 'FLECHAS DE TIRO AL ARCO', 105859, 0, NULL, 105855, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105860, 49181604, 105860, 'DARDOS', 105860, 0, NULL, 105855, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105861, 49181605, 105861, 'DIANAS PARA DARDOS', 105861, 0, NULL, 105855, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105862, 49181606, 105862, 'TIRO AL PLATO', 105862, 0, NULL, 105855, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(133727, 49181607, 133727, 'BLANCOS ARROJADIZOS', 133727, 0, NULL, 105855, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(133728, 49181608, 133728, 'CUERDAS DE ARCO DE TIRO CON ARCO', 133728, 0, NULL, 105855, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(133729, 49181609, 133729, 'GUANTES DE TIRO CON ARCO', 133729, 0, NULL, 105855, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(133730, 49181610, 133730, 'PROTECTORES DE BRAZO DE TIRO CON ARCO', 133730, 0, NULL, 105855, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(133731, 49181611, 133731, 'SOPORTES DE DIANAS DE TIRO CON ARCO', 133731, 0, NULL, 105855, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(133732, 49181612, 133732, 'DELIMITADORES DE CAMPO DE TIRO CON ARCO', 133732, 0, NULL, 105855, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105865, 49201501, 105865, 'TAPICES RODANTES', 105865, 0, NULL, 105864, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105866, 49201502, 105866, 'ESCALONES', 105866, 0, NULL, 105864, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105867, 49201503, 105867, 'BICICLETAS ESTATICAS', 105867, 0, NULL, 105864, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105868, 49201504, 105868, 'MAQUINAS DE REMO', 105868, 0, NULL, 105864, 4,'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105876, 49201504, 105876, 'CUERDAS PARA SALTAR', 105876, 0, NULL, 105864, 4,'SYSADMIN', CURRENT_TIMES(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(105877, 49201513, 105877, 'CAMAS ELASTICAS PARA EJERCICIOS', 105877, 0, NULL, 105864, 4,'SYSADMIN', CURRENT_TIMES(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(133733, 49201514, 133733, 'PELOTAS DE EJERCICIO', 133733, 0, NULL, 105864, 4,'SYSADMIN', CURRENT_TIMES(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(133734, 49201515, 133734, 'EQUIPO DE STEP AEROBIC', 133734, 0, NULL, 105864, 4,'SYSADMIN', CURRENT_TIMES(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO INV_CLASIFICADOR (N_ID, N_CBS, N_CLASIFICACION, C_DESCRIPCION, N_IDENTIFICADOR, B_RESTRINGIDO, C_SINONIMOS, N_ID_ELEMENTOPADRE, N_TIPOCLASIFICADOR, C_CUSER, D_CTIME, C_MUSER, D_MTIME)
VALUES(136592, 49201516, 136592, 'MAQUINAS MIXTAS DE EJERCICIO (CROSS TRAINER)', 136592, 0, NULL, 105864, 4,'SYSADMIN', CURRENT_TIMES(), 'SYSADMIN', CURRENT_TIMESTAMP());
