--INSERTAR SERVICIOS
INSERT INTO SEG_SERVICIO (N_ID, C_NOMBRE, C_DESCRIPCION, D_CTIME, C_CUSER, D_MTIME, C_MUSER)
VALUES (0, 'CONTAC', 'Contac Project', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP, 'SYSADMIN');
INSERT INTO SEG_SERVICIO (N_ID, C_NOMBRE, C_DESCRIPCION, D_CTIME, C_CUSER, D_MTIME, C_MUSER, N_ID_SERVICIOPADRE)
VALUES (1, 'SEGURIDAD', 'Seguridad', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', 0);
INSERT INTO SEG_SERVICIO (N_ID, C_NOMBRE, C_DESCRIPCION, D_CTIME, C_CUSER, D_MTIME, C_MUSER, N_ID_SERVICIOPADRE)
VALUES (2, 'ADMINISTRACION', 'Administracion', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', 0);
INSERT INTO SEG_SERVICIO (N_ID, C_NOMBRE, C_DESCRIPCION, D_CTIME, C_CUSER, D_MTIME, C_MUSER, N_ID_SERVICIOPADRE)
VALUES (3, 'CATALOGO PRODUCTOS', 'Catalogo Productos', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', 0);
INSERT INTO SEG_SERVICIO (N_ID, C_NOMBRE, C_DESCRIPCION, D_CTIME, C_CUSER, D_MTIME, C_MUSER, N_ID_SERVICIOPADRE)
VALUES (4, 'PROVEEDORES', 'Proveedores', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', 0);
INSERT INTO SEG_SERVICIO (N_ID, C_NOMBRE, C_DESCRIPCION, D_CTIME, C_CUSER, D_MTIME, C_MUSER, N_ID_SERVICIOPADRE)
VALUES (5, 'INVENTARIO', 'Inventario', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', 0);
INSERT INTO SEG_SERVICIO (N_ID, C_NOMBRE, C_DESCRIPCION, D_CTIME, C_CUSER, D_MTIME, C_MUSER, N_ID_SERVICIOPADRE)
VALUES (6, 'FACTURACION', 'Facturacion', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', 0);
INSERT INTO SEG_SERVICIO (N_ID, C_NOMBRE, C_DESCRIPCION, D_CTIME, C_CUSER, D_MTIME, C_MUSER, N_ID_SERVICIOPADRE)
VALUES (7, 'CLIENTES', 'Clientes', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', 0);

--INSERTAR PERMISOS
INSERT INTO SEG_PERMISO (N_ID, C_NOMBRE, C_DESCRIPCION, D_CTIME, C_CUSER, D_MTIME, C_MUSER) VALUES(1, 'VIEW', 'View', CURRENT_TIMESTAMP, 'SYSADMIN', CURRENT_TIMESTAMP, 'SYSADMIN');
INSERT INTO SEG_PERMISO (N_ID, C_NOMBRE, C_DESCRIPCION, D_CTIME, C_CUSER, D_MTIME, C_MUSER) VALUES(2, 'INSERT', 'Insert', CURRENT_TIMESTAMP, 'SYSADMIN', CURRENT_TIMESTAMP, 'SYSADMIN');
INSERT INTO SEG_PERMISO (N_ID, C_NOMBRE, C_DESCRIPCION, D_CTIME, C_CUSER, D_MTIME, C_MUSER) VALUES(3, 'UPDATE', 'Update', CURRENT_TIMESTAMP, 'SYSADMIN', CURRENT_TIMESTAMP, 'SYSADMIN');
INSERT INTO SEG_PERMISO (N_ID, C_NOMBRE, C_DESCRIPCION, D_CTIME, C_CUSER, D_MTIME, C_MUSER) VALUES(4, 'DELETE', 'Delete', CURRENT_TIMESTAMP, 'SYSADMIN', CURRENT_TIMESTAMP, 'SYSADMIN');
INSERT INTO SEG_PERMISO (N_ID, C_NOMBRE, C_DESCRIPCION, D_CTIME, C_CUSER, D_MTIME, C_MUSER) VALUES(5, 'EXECUTE', 'Execute', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP, 'SYSADMIN');

--INSERTAR ROLES
INSERT INTO SEG_ROL (N_ID, C_NOMBRE, C_DESCRIPCION, D_CTIME, C_CUSER, D_MTIME, C_MUSER, N_ID_SERVICIO)
VALUES (1, 'ROLCONTACAUTHSERVICEADMIN', 'ADMINISTRADOR SERVICIO AUTENTICACION', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', 1);
INSERT INTO SEG_ROL (N_ID, C_NOMBRE, C_DESCRIPCION, D_CTIME, C_CUSER, D_MTIME, C_MUSER, N_ID_SERVICIO)
VALUES (2, 'ROLSYSTEMADMIN', 'ADMINISTRADOR DE SISTEMA', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', 0);
INSERT INTO SEG_ROL (N_ID, C_NOMBRE, C_DESCRIPCION, D_CTIME, C_CUSER, D_MTIME, C_MUSER, N_ID_SERVICIO)
VALUES (3, 'ROLCONTACSERVICEADMIN', 'ADMINISTRADOR SERVIDOR', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', 2);
INSERT INTO SEG_ROL (N_ID, C_NOMBRE, C_DESCRIPCION, D_CTIME, C_CUSER, D_MTIME, C_MUSER, N_ID_SERVICIO)
VALUES (4, 'ROLCATALOGOADMIN', 'ADMINISTRADOR CATALOGOS', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', 3);
INSERT INTO SEG_ROL (N_ID, C_NOMBRE, C_DESCRIPCION, D_CTIME, C_CUSER, D_MTIME, C_MUSER, N_ID_SERVICIO)
VALUES (5, 'ROLCONTACSERVICEAPP', 'ADMINISTRADOR SERVICIO APLICATIVO', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP, 'SYSADMIN', 0);
INSERT INTO SEG_ROL (N_ID, C_NOMBRE, C_DESCRIPCION, D_CTIME, C_CUSER, D_MTIME, C_MUSER, N_ID_SERVICIO)
VALUES (6, 'ROLCATALOGOCONSULTA', 'CONSULTA DE CATALOGOS', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP, 'SYSADMIN', 3);
INSERT INTO SEG_ROL (N_ID, C_NOMBRE, C_DESCRIPCION, D_CTIME, C_CUSER, D_MTIME, C_MUSER, N_ID_SERVICIO)
VALUES (7, 'ROLCOMPANIAADMIN', 'ADMINISTRADOR DE COMPANIAS', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP, 'SYSADMIN', 2);
INSERT INTO SEG_ROL (N_ID, C_NOMBRE, C_DESCRIPCION, D_CTIME, C_CUSER, D_MTIME, C_MUSER, N_ID_SERVICIO)
VALUES (8, 'ROLCATALOGOPRODUCTOCONSULTA', 'CONSULTA CATALOGO DE PRODUCTOS', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP, 'SYSADMIN', 5);
INSERT INTO SEG_ROL (N_ID, C_NOMBRE, C_DESCRIPCION, D_CTIME, C_CUSER, D_MTIME, C_MUSER, N_ID_SERVICIO)
VALUES (9, 'ROLCATALOGOPRODUCTOADMIN', 'ADMINISTRADOR DE CATALOGO DE PRODUCTOS', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP, 'SYSADMIN', 3);
INSERT INTO SEG_ROL (N_ID, C_NOMBRE, C_DESCRIPCION, D_CTIME, C_CUSER, D_MTIME, C_MUSER, N_ID_SERVICIO)
VALUES (10, 'ROLINVENTARIOADMIN', 'ADMINISTRADOR DE INVENTARIOS', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP, 'SYSADMIN', 5);
INSERT INTO SEG_ROL (N_ID, C_NOMBRE, C_DESCRIPCION, D_CTIME, C_CUSER, D_MTIME, C_MUSER, N_ID_SERVICIO)
VALUES (11, 'ROLCONTACUSER', 'USUARIO SISTEMA CONTAC BUSINESS', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP, 'SYSADMIN', 1);
INSERT INTO SEG_ROL (N_ID, C_NOMBRE, C_DESCRIPCION, D_CTIME, C_CUSER, D_MTIME, C_MUSER, N_ID_SERVICIO)
VALUES (12, 'ROLCLIENTEADMIN', 'ADMINISTRADOR DE CLIENTES', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP, 'SYSADMIN', 7);
INSERT INTO SEG_ROL (N_ID, C_NOMBRE, C_DESCRIPCION, D_CTIME, C_CUSER, D_MTIME, C_MUSER, N_ID_SERVICIO)
VALUES (13, 'ROLPROVEEDORADMIN', 'ADMINISTRADOR DE PROVEEDORES', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP, 'SYSADMIN', 4);
INSERT INTO SEG_ROL (N_ID, C_NOMBRE, C_DESCRIPCION, D_CTIME, C_CUSER, D_MTIME, C_MUSER, N_ID_SERVICIO)
VALUES (14, 'ROLFACTURACION', 'VENTAS DE ARTICULOS', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP, 'SYSADMIN', 6);
INSERT INTO SEG_ROL (N_ID, C_NOMBRE, C_DESCRIPCION, D_CTIME, C_CUSER, D_MTIME, C_MUSER, N_ID_SERVICIO)
VALUES (15, 'ROLFACTURACIONADMIN', 'ADMINISTRADOR MODULO DE VENTAS', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP, 'SYSADMIN', 6);
INSERT INTO SEG_ROL (N_ID, C_NOMBRE, C_DESCRIPCION, D_CTIME, C_CUSER, D_MTIME, C_MUSER, N_ID_SERVICIO)
VALUES (16, 'ROLCAJAADMIN', 'CAJERO', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP, 'SYSADMIN', 6);

--INSERTAR USUARIOS
INSERT INTO SEG_USUARIO (C_USERNAME, C_PASSWORD, C_ESTADO, D_CTIME, C_CUSER, D_MTIME, C_MUSER)
VALUES ('SYSADMIN', 'ef6299c9e7fdae6d775819ce1e2620b8', 'ACTIVO', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN');

--INSERTAR USUARIOS-ROLES
INSERT INTO SEG_USUARIO_ROL (C_USERNAME, N_ID_ROL) VALUES ('SYSADMIN', 1);
INSERT INTO SEG_USUARIO_ROL (C_USERNAME, N_ID_ROL) VALUES ('SYSADMIN', 2);
INSERT INTO SEG_USUARIO_ROL (C_USERNAME, N_ID_ROL) VALUES ('SYSADMIN', 3);
INSERT INTO SEG_USUARIO_ROL (C_USERNAME, N_ID_ROL) VALUES ('SYSADMIN', 4);
INSERT INTO SEG_USUARIO_ROL (C_USERNAME, N_ID_ROL) VALUES ('SYSADMIN', 5);
INSERT INTO SEG_USUARIO_ROL (C_USERNAME, N_ID_ROL) VALUES ('SYSADMIN', 6);
INSERT INTO SEG_USUARIO_ROL (C_USERNAME, N_ID_ROL) VALUES ('SYSADMIN', 7);
INSERT INTO SEG_USUARIO_ROL (C_USERNAME, N_ID_ROL) VALUES ('SYSADMIN', 8);
INSERT INTO SEG_USUARIO_ROL (C_USERNAME, N_ID_ROL) VALUES ('SYSADMIN', 9);
INSERT INTO SEG_USUARIO_ROL (C_USERNAME, N_ID_ROL) VALUES ('SYSADMIN', 10);
INSERT INTO SEG_USUARIO_ROL (C_USERNAME, N_ID_ROL) VALUES ('SYSADMIN', 11);
INSERT INTO SEG_USUARIO_ROL (C_USERNAME, N_ID_ROL) VALUES ('SYSADMIN', 12);
INSERT INTO SEG_USUARIO_ROL (C_USERNAME, N_ID_ROL) VALUES ('SYSADMIN', 13);
INSERT INTO SEG_USUARIO_ROL (C_USERNAME, N_ID_ROL) VALUES ('SYSADMIN', 14);
INSERT INTO SEG_USUARIO_ROL (C_USERNAME, N_ID_ROL) VALUES ('SYSADMIN', 15);



