/*
 *
 * Created on 12 de noviembre de 2008, 09:08 PM
 */

package contac.servicio.app.panel;

import contac.commons.form.panel.GenericFrame;
import contac.commons.form.render.cls_Nodo;
import contac.commons.form.render.cls_RenderNode;
import contac.servicio.app.util.Util;

import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author  hmurbina
 */
public class pnlClientes extends pnl_Generico{
    
    private JTree arbolProyectos;
  
    public pnlClientes(GenericFrame mdi) {
        this.setMDI(mdi);
        initComponents();
        this.establecerConfiguracion();
    }

    public void establecerConfiguracion(){  
        cls_Nodo raiz = new cls_Nodo("CLIENTES");
        raiz.setTipoNodo(cls_Nodo.Raiz);
        this.cargarProyectos(raiz);
        Util u = new Util();
        u.expandTree(this.arbolProyectos,true);
    }
    
    // <editor-fold defaultstate="collapsed" desc="PROYECT LOADERS">
    
    public void reloadProyects(){
        DefaultTreeModel model = (DefaultTreeModel)this.arbolProyectos.getModel();
        model.setRoot(null);
        this.arbolProyectos.setModel(model);
        this.establecerConfiguracion();

    }

    //cargo los proyectos en ejecucion
    private void cargarProyectos(DefaultMutableTreeNode raiz){

        cls_Nodo fondos = new cls_Nodo("Clientes Activos");
        fondos.setTipoNodo(cls_Nodo.Proyectos);
        raiz.add(fondos);
        this.cargarOpcionesDeProyecto(fondos, false);

        cls_Nodo nodo = new cls_Nodo("Clientes Morosos");
        nodo.setId("1");
        nodo.setTipoNodo(cls_Nodo.Proyectos);
        this.cargarOpcionesDeProyecto(nodo, true);
        raiz.add(nodo);

        cls_Nodo nodo_presupuesto = new cls_Nodo("Clientes Inactivos");
        nodo_presupuesto.setTipoNodo(cls_Nodo.Raiz_Presupuesto);
        raiz.add(nodo_presupuesto);

        this.cargarPresupuestos(nodo_presupuesto);

        this.arbolProyectos = new JTree(raiz);
        this.jScrollPane1.setViewportView(this.arbolProyectos);
        this.arbolProyectos.setComponentPopupMenu(jPopupMenu1);
        this.cambiarApariencia();

    }
    
    //cargo las opciones de los proyectos
    private void cargarOpcionesDeProyecto(cls_Nodo proyecto,boolean presupuesto){
        String[] opcion = {"Mayling Chuang",
                           "Jenniffer Peng",
                           "Josffa Koothrapalli"};
        
        String[][] tipo = {cls_Nodo.ComprobantesDiario,
                           cls_Nodo.ComprobantesCheque,
                           cls_Nodo.Presupuesto_Asignado};

        int largo = opcion.length;
        if(!presupuesto){
            largo = opcion.length-1;
        }
        for (int i = 0; i < largo; i++) {
            cls_Nodo nodoOpcion = new cls_Nodo(opcion[i]);
            nodoOpcion.setTipoNodo(tipo[i]);
            proyecto.add(nodoOpcion);
        }
    }
// </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="PRESUPUESTO LOADERS">
    
    //cargo los presupuestos sin asignar
    public void cargarPresupuestos(DefaultMutableTreeNode raiz) {
        cls_Nodo nodo = new cls_Nodo("PROINCASA");
        nodo.setId("2");
        nodo.setTipoNodo(cls_Nodo.Presupuesto);
        raiz.add(nodo);
    }
    
// </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="RENDERER">
    
    public void cambiarApariencia(){
        this.arbolProyectos.setCellRenderer(new cls_RenderNode());
    }
// </editor-fold>    


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        menuNuevoPresupuesto = new javax.swing.JMenuItem();
        menuNuevoProyecto = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        menuEliminar = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jXHeader1 = new org.jdesktop.swingx.JXHeader();

        jPopupMenu1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jPopupMenu1PopupMenuWillBecomeVisible(evt);
            }
        });

        menuNuevoPresupuesto.setText("Nuevo Presupuesto");
        menuNuevoPresupuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNuevoPresupuestoActionPerformed(evt);
            }
        });
        jPopupMenu1.add(menuNuevoPresupuesto);

        menuNuevoProyecto.setText("Nuevo Proyecto");
        menuNuevoProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNuevoProyectoActionPerformed(evt);
            }
        });
        jPopupMenu1.add(menuNuevoProyecto);
        jPopupMenu1.add(jSeparator1);

        menuEliminar.setText("Eliminar Presupuesto");
        menuEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEliminarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(menuEliminar);

        setLayout(new java.awt.BorderLayout());
        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jXHeader1.setDescription("");
        jXHeader1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jXHeader1.setTitle("Clientes");
        add(jXHeader1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

private void jPopupMenu1PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jPopupMenu1PopupMenuWillBecomeVisible
// TODO add your handling code here:
    
}//GEN-LAST:event_jPopupMenu1PopupMenuWillBecomeVisible

private void menuEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEliminarActionPerformed
    
}//GEN-LAST:event_menuEliminarActionPerformed

private void menuNuevoPresupuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNuevoPresupuestoActionPerformed
   
}//GEN-LAST:event_menuNuevoPresupuestoActionPerformed

private void menuNuevoProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNuevoProyectoActionPerformed
    
}//GEN-LAST:event_menuNuevoProyectoActionPerformed
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private org.jdesktop.swingx.JXHeader jXHeader1;
    private javax.swing.JMenuItem menuEliminar;
    private javax.swing.JMenuItem menuNuevoPresupuesto;
    private javax.swing.JMenuItem menuNuevoProyecto;
    // End of variables declaration//GEN-END:variables
  
}
