/**
 * Copyright 2012 Contac Business Software. All rights reserved.
 * CONTAC PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */

/*
 * pnlAdmonBancos.java
 *
 * Created on 02-16-2012, 11:23:05 PM
 */
package contac.administracion.moneda.app;

import contac.administracion.controller.BancoController;
import contac.commons.form.label.JOptionErrorPane;
import contac.commons.form.label.JOptionMessagePane;
import contac.commons.form.panel.GenericFrame;
import contac.internationalization.LanguageLocale;
import contac.modelo.entity.Banco;
import org.apache.log4j.Logger;

import javax.swing.*;
import java.awt.*;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ResourceBundle;

/**
 * @author EMontenegro
 */
public class pnlAdmonBancos extends JDialog {

    //Apache log4j
    private static final Logger logger = Logger.getLogger(pnlAdmonBancos.class);

    //Message Resource Bundle
    private ResourceBundle messageBundle = ResourceBundle.getBundle("contac/administracion/app/mensajes/Mensajes",
            LanguageLocale.getInstance().getLocale());

    //Controller
    private BancoController controller;


    /**
     * Creates new form pnlAdmonBancos
     */
    public pnlAdmonBancos(GenericFrame frame, boolean modal, Banco entity) {

        //Call super constructor
        super(frame, modal);

        //Setting controller
        this.controller = new BancoController();

        //Init controller
        this.controller.init();

        if (entity != null) {
            this.controller.setBanco(entity);
            this.controller.initModificacion();
        }

        //Init components
        initComponents();

        //Init values
        initBancosComponents();

        //Register listeners
        registerListeners();

        //Show panel
        showPanel();
    }

    /**
     * This method is called from within the constructor to
     * show the JDialog form
     */
    private void showPanel() {
        setTitle(messageBundle.getString("CONTAC.FORM.ADMINISTRABANCOS"));
        this.setLocation(400, 300);
        this.setSize(new Dimension(600, 250));
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to
     * initialize the components of the form
     */
    private void initBancosComponents() {

        //<Nombre Comercial>
        txtNombreComercial.setText(controller.getNombreComercial());
        //<Razon Social>
        txtRazonSocial.setText(controller.getRazonSocial());

        //<Focus request>
        txtNombreComercial.requestFocusInWindow();
    }

    /**
     * This method is called from within the constructor to
     * initialize the behavior of the components of the form
     */
    private void registerListeners() {

        //<txtNombreComercial>
        txtNombreComercial.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {

                if (e.VK_ENTER == e.getKeyChar()) {
                    txtRazonSocial.requestFocusInWindow();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleHeader = new org.jdesktop.swingx.JXHeader();
        frmAdmonBancos = new javax.swing.JPanel();
        tbAcciones = new javax.swing.JToolBar();
        btnNuevo = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnGuardar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnRemover = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnLimpiar = new javax.swing.JButton();
        frmDatosGenerales = new javax.swing.JPanel();
        lblNombreComercial = new javax.swing.JLabel();
        lblRazonSocial = new javax.swing.JLabel();
        txtNombreComercial = new javax.swing.JTextField();
        txtRazonSocial = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titleHeader.setBackground(new java.awt.Color(204, 204, 204));
        titleHeader.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        titleHeader.setPreferredSize(new java.awt.Dimension(51, 40));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("contac/administracion/app/mensajes/Mensajes_es"); // NOI18N
        titleHeader.setTitle(bundle.getString("CONTAC.FORM.ADMINISTRABANCOS")); // NOI18N
        titleHeader.setTitleForeground(new java.awt.Color(255, 153, 0));
        getContentPane().add(titleHeader, java.awt.BorderLayout.NORTH);

        frmAdmonBancos.setLayout(new java.awt.BorderLayout());

        tbAcciones.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tbAcciones.setMaximumSize(new java.awt.Dimension(124, 32));
        tbAcciones.setMinimumSize(new java.awt.Dimension(124, 32));

        btnNuevo.setIcon(new ImageIcon(getClass().getResource("/contac/resources/icons/actions/new.png")));
        btnNuevo.setToolTipText(bundle.getString("CONTAC.FORM.BTNNUEVO")); // NOI18N
        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNuevo.setFocusable(false);
        btnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnNuevo.setMaximumSize(new java.awt.Dimension(40, 32));
        btnNuevo.setMinimumSize(new java.awt.Dimension(40, 32));
        btnNuevo.setPreferredSize(new java.awt.Dimension(40, 32));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        tbAcciones.add(btnNuevo);
        tbAcciones.add(jSeparator1);

        btnGuardar.setIcon(new ImageIcon(getClass().getResource("/contac/resources/icons/actions/save.png")));
        btnGuardar.setToolTipText(bundle.getString("CONTAC.FORM.BTNGUARDAR")); // NOI18N
        btnGuardar.setFocusable(false);
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setMaximumSize(new java.awt.Dimension(40, 32));
        btnGuardar.setMinimumSize(new java.awt.Dimension(40, 32));
        btnGuardar.setName(""); // NOI18N
        btnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        tbAcciones.add(btnGuardar);
        tbAcciones.add(jSeparator2);

        btnRemover.setIcon(new ImageIcon(getClass().getResource("/contac/resources/icons/actions/remove.png")));
        btnRemover.setToolTipText(bundle.getString("CONTAC.FORM.BTNREMOVER")); // NOI18N
        btnRemover.setEnabled(false);
        btnRemover.setFocusable(false);
        btnRemover.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnRemover.setMaximumSize(new java.awt.Dimension(40, 32));
        btnRemover.setMinimumSize(new java.awt.Dimension(40, 32));
        btnRemover.setName(""); // NOI18N
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });
        tbAcciones.add(btnRemover);
        tbAcciones.add(jSeparator3);

        btnLimpiar.setIcon(new ImageIcon(getClass().getResource("/contac/resources/icons/actions/reload.png")));
        btnLimpiar.setToolTipText(bundle.getString("CONTAC.FORM.BTNACTUALIZAR")); // NOI18N
        btnLimpiar.setFocusable(false);
        btnLimpiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLimpiar.setMaximumSize(new java.awt.Dimension(40, 32));
        btnLimpiar.setMinimumSize(new java.awt.Dimension(40, 32));
        btnLimpiar.setName(""); // NOI18N
        btnLimpiar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        tbAcciones.add(btnLimpiar);

        frmAdmonBancos.add(tbAcciones, java.awt.BorderLayout.PAGE_START);

        lblNombreComercial.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombreComercial.setText(bundle.getString("CONTAC.FORM.ADMINISTRACOMPANIA.NOMBRECOMERCIAL")); // NOI18N

        lblRazonSocial.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRazonSocial.setText(bundle.getString("CONTAC.FORM.ADMINISTRACOMPANIA.RAZONSOCIAL")); // NOI18N

        txtNombreComercial.setToolTipText("");
        txtNombreComercial.setMinimumSize(new java.awt.Dimension(6, 25));
        txtNombreComercial.setPreferredSize(new java.awt.Dimension(59, 30));

        txtRazonSocial.setToolTipText("");
        txtRazonSocial.setMinimumSize(new java.awt.Dimension(6, 25));
        txtRazonSocial.setPreferredSize(new java.awt.Dimension(59, 30));

        javax.swing.GroupLayout frmDatosGeneralesLayout = new javax.swing.GroupLayout(frmDatosGenerales);
        frmDatosGenerales.setLayout(frmDatosGeneralesLayout);
        frmDatosGeneralesLayout.setHorizontalGroup(
            frmDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmDatosGeneralesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frmDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frmDatosGeneralesLayout.createSequentialGroup()
                        .addComponent(lblNombreComercial, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombreComercial, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE))
                    .addGroup(frmDatosGeneralesLayout.createSequentialGroup()
                        .addComponent(lblRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtRazonSocial, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)))
                .addContainerGap())
        );
        frmDatosGeneralesLayout.setVerticalGroup(
            frmDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmDatosGeneralesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frmDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreComercial, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreComercial, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(frmDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        frmAdmonBancos.add(frmDatosGenerales, java.awt.BorderLayout.CENTER);

        getContentPane().add(frmAdmonBancos, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed

        //Init properties values
        controller.init();

        //Init bancos components
        initBancosComponents();

    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        try {

            //Validar datos form
            validarDatosForm();

            //Setting properties
            controller.setNombreComercial(txtNombreComercial.getText());
            controller.setRazonSocial(txtRazonSocial.getText());

            //Save data
            if (!controller.is_edit()) {

                //Registrar banco
                controller.registrarBanco();

                //Show confirmation message
                JOptionErrorPane.showMessageInfo(null, messageBundle.getString("CONTAC.FORM.MSG.CONFIRMACION"),
                        messageBundle.getString("CONTAC.FORM.MSG.BANCO.INGRESO.EXITOSO"));
            }

            if (controller.is_edit()) {

                //Modificar banco
                controller.modicarBanco();

                //Show confirmation message
                JOptionErrorPane.showMessageInfo(null, messageBundle.getString("CONTAC.FORM.MSG.CONFIRMACION"),
                        messageBundle.getString("CONTAC.FORM.MSG.BANCO.MODIFICACION.EXITOSO"));
            }


            //Init bancos components
            initBancosComponents();

        } catch (Exception e) {
            logger.error(e.getMessage(), e);
            JOptionErrorPane.showMessageError(null, messageBundle.getString("CONTAC.FORM.MSG.ERROR.REGISTRO"),
                    e.getMessage());
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        //Init properties values
        controller.init();

        //Init bancos components
        initBancosComponents();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed

        try {

            boolean confirmation = JOptionMessagePane.showConfirmationInfo(null, messageBundle.getString("CONTAC.FORM.MSG.ADVERTENCIA"),
                    messageBundle.getString("CONTAC.FORM.MSG.BANCO.REMOVER.CONFIRMA"));

            if (confirmation) {

                //Remover banco
                controller.removerBanco();

                //Show confirmation message
                JOptionErrorPane.showMessageInfo(null, messageBundle.getString("CONTAC.FORM.MSG.CONFIRMACION"),
                        messageBundle.getString("CONTAC.FORM.MSG.BANCO.REMOVER.EXITOSO"));

            }

        } catch (Exception e) {
            logger.error(e.getMessage(), e);
            JOptionErrorPane.showMessageError(null, messageBundle.getString("CONTAC.FORM.MSG.ERROR.REGISTRO"),
                    e.getMessage());
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    /**
     * Valida datos obligatorios para registro y modificacion *
     */
    private void validarDatosForm() throws Exception {

        //Nombre comercial
        if (txtNombreComercial.getText().equals("")) {
            //Request focus
            txtNombreComercial.requestFocus();
            txtNombreComercial.selectAll();
            //Throw error message
            throw new Exception(messageBundle.getString("CONTAC.FORM.ADMINISTRACOMPANIA.NOMBRECOMERCIAL.VALIDA"));
        }

        //Razon social
        if (txtRazonSocial.getText().equals("")) {
            //Request focus
            txtRazonSocial.requestFocus();
            txtRazonSocial.selectAll();
            //Throw error message
            throw new Exception(messageBundle.getString("CONTAC.FORM.ADMINISTRACOMPANIA.RAZONSOCIAL.VALIDA"));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRemover;
    private javax.swing.JPanel frmAdmonBancos;
    private javax.swing.JPanel frmDatosGenerales;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JLabel lblNombreComercial;
    private javax.swing.JLabel lblRazonSocial;
    private javax.swing.JToolBar tbAcciones;
    private org.jdesktop.swingx.JXHeader titleHeader;
    private javax.swing.JTextField txtNombreComercial;
    private javax.swing.JTextField txtRazonSocial;
    // End of variables declaration//GEN-END:variables
}
