/**
 * Copyright 2011 Contac Business Software. All rights reserved.
 * CONTAC PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */

/*
 * pnlOrdenEntradaInventario.java
 *
 * Created on 12-17-2011, 10:52:00 PM
 */
package contac.inventarios.movimiento.inventario.app;

import contac.commons.form.label.JOptionErrorPane;
import contac.commons.form.label.JOptionMessagePane;
import contac.commons.form.layout.XYConstraints;
import contac.commons.form.layout.XYLayout;
import contac.commons.form.panel.GenericFrame;
import contac.commons.form.panel.GenericPanel;
import contac.commons.form.render.*;
import contac.commons.models.comboBox.AlmacenComboBoxModel;
import contac.commons.models.comboBox.ComboBoxEmptySelectionRenderer;
import contac.commons.models.comboBox.TipoFacturaComboBoxModel;
import contac.commons.models.tables.BeanTableModel;
import contac.internationalization.LanguageLocale;
import contac.inventarios.controller.OrdenEntradaController;
import contac.modelo.entity.*;
import org.apache.log4j.Logger;
import org.jdesktop.swingx.JXDatePicker;
import org.jdesktop.swingx.JXHeader;

import javax.swing.*;
import javax.swing.table.TableColumnModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.MessageFormat;
import java.util.Date;
import java.util.Locale;
import java.util.ResourceBundle;

/**
 * @author EMontenegro
 */
public class pnlRegistroOrdenesEntradaInventario extends GenericPanel {

    //Apache log4j
    private static final Logger logger = Logger.getLogger(pnlRegistroOrdenesEntradaInventario.class);

    //Controller
    private OrdenEntradaController controller;

    //Message resource bundle
    private ResourceBundle messageBundle = ResourceBundle.getBundle("contac/inventarios/app/mensajes/Mensajes",
            LanguageLocale.getInstance().getLocale());

    private JXHeader header;
    /**
     * Creates new form pnlOrdenEntradaInventario
     */
    public pnlRegistroOrdenesEntradaInventario(GenericFrame frame) {

        //Call super constructor
        super(frame, "OrdenEntradaAlmacen", "Orden de Entrada en Almac\u00e9n", true, "contac/inventarios/app/mensajes/Mensajes",
                new Locale("es", "NIC"));

        //Controller
        controller = new OrdenEntradaController();

        try {

            //Init registros de datos
            controller.initRegistrosOrdenesEntradaInventario();

            //Init components
            initComponents();

            //Init values
            initValues();

            //Init Action Listeners
            initActionListeners();

        } catch (Exception e) {
            logger.error(e.getMessage(), e);
            JOptionErrorPane.showMessageError(null, messageBundle.getString("CONTAC.FORM.ADMINISTRAPRODUCTO.ERROR.BUSQUEDA"),
                    e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        //***************************************************************************************
        //Init Header Panel
        //***************************************************************************************
        header = new JXHeader();
        header.setTitle(messageBundle.getString("CONTAC.FORM.ADMINISTRAPRODUCTO.TITTLEORDEN")); // NOI18N
        header.setForeground(new java.awt.Color(255, 153, 0));
        header.setTitleForeground(new java.awt.Color(255, 153, 0));
        header.setPreferredSize(new Dimension(50, 35));

        headerAlmacenes = new org.jdesktop.swingx.JXHeader();
        pnlRegistroInventario = new JPanel(new BorderLayout());
        pnlRegistroInventario.setBorder(BorderFactory.createEtchedBorder());
        scrollOrdenesEntrada = new javax.swing.JScrollPane();
        tblOrdenesEntrada = new org.jdesktop.swingx.JXTable();
        tbRegistroInventarios = new javax.swing.JToolBar();
        pnlRegistroProformasWest = new JPanel();
        btnAgregar = new javax.swing.JButton();
        separatorOne = new javax.swing.JToolBar.Separator();
        btnEditar = new javax.swing.JButton();
        separatorTwo = new javax.swing.JToolBar.Separator();
        btnAnular = new javax.swing.JButton();
        scrollProformasClientes = new JScrollPane();
        scrollProformaWest = new JScrollPane();
        //*********************************************************************
        //Create Search Panel
        //*********************************************************************

        JPanel searchPanel = new JPanel(new XYLayout());
        searchPanel.setBorder(BorderFactory.createEtchedBorder());
        searchPanel.setPreferredSize(new Dimension(340, 400));

        lblFechaDesde = new JLabel(messageBundle.getString("CONTAC.FORM.ADMINISTRAPRODUCTO.FECHADESDE"));


        lblFechaDesde.setHorizontalAlignment(JLabel.LEFT);

        lblFechaHasta = new JLabel(messageBundle.getString("CONTAC.FORM.ADMINISTRAPRODUCTO.FECHAHASTA"));
        lblFechaHasta.setHorizontalAlignment(JLabel.LEFT);

        lblAlmacen = new JLabel(messageBundle.getString("CONTAC.FORM.ADMINISTRAPRODUCTO.ALMACEN"));
        lblAlmacen.setHorizontalAlignment(JLabel.LEFT);

        dtpFechaDesde = new JXDatePicker();
        dtpFechaHasta = new JXDatePicker();

        //cmbTipoFactura = new JComboBox();
        cmbAlmacen = new JComboBox();

        ImageIcon buscarIco = new ImageIcon(getClass().getResource("/contac/resources/icons/search.png"));
        ImageIcon cancelarIco = new ImageIcon(getClass().getResource("/contac/resources/icons/actions/remove2.png"));

        btnBuscar = new JButton(messageBundle.getString("CONTAC.FORM.BTNBUSCAR"));
        btnBuscar.setIcon(buscarIco);

        btnCancelar = new JButton(messageBundle.getString("CONTAC.FORM.BTNCANCELAR"));
        btnCancelar.setIcon(cancelarIco);

        searchPanel.add(lblFechaDesde, new XYConstraints(5, 5, 120, 23));
        searchPanel.add(dtpFechaDesde, new XYConstraints(130, 5, 120, 23));
        searchPanel.add(lblFechaHasta, new XYConstraints(5, 33, 120, 23));
        searchPanel.add(dtpFechaHasta, new XYConstraints(130, 33, 120, 23));
        searchPanel.add(lblAlmacen, new XYConstraints(5, 61, 90, 23));
        searchPanel.add(cmbAlmacen, new XYConstraints(130, 61, 200, 23));
        searchPanel.add(btnBuscar, new XYConstraints(75, 89, 90, 23));
        searchPanel.add(btnCancelar, new XYConstraints(175, 89, 90, 23));

        //*********************************************************************
        //Create Facturas table
        //*********************************************************************



        setLayout(new java.awt.BorderLayout());

        headerAlmacenes.setForeground(new java.awt.Color(255, 153, 0));
        headerAlmacenes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        headerAlmacenes.setPreferredSize(new java.awt.Dimension(51, 35));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("contac/inventarios/app/mensajes/Mensajes_es"); // NOI18N
        headerAlmacenes.setTitle(bundle.getString("CONTAC.FORM.ORDENENTRADA.TITLE")); // NOI18N
        headerAlmacenes.setTitleForeground(new java.awt.Color(255, 153, 0));
        add(headerAlmacenes, java.awt.BorderLayout.NORTH);

        pnlRegistroInventario.setLayout(new java.awt.BorderLayout());

        tblOrdenesEntrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblOrdenesEntradaMouseClicked(evt);
            }
        });
        scrollOrdenesEntrada.setViewportView(tblOrdenesEntrada);

        pnlRegistroInventario.add(scrollOrdenesEntrada, java.awt.BorderLayout.CENTER);

        //tbRegistroInventarios.setBorder(null);
        tbRegistroInventarios.setMaximumSize(new java.awt.Dimension(124, 32));
        tbRegistroInventarios.setMinimumSize(new java.awt.Dimension(124, 32));
        tbRegistroInventarios.setPreferredSize(new java.awt.Dimension(124, 32));

        btnAgregar.setIcon(new ImageIcon(getClass().getResource("/contac/resources/icons/actions/new.png")));
        btnAgregar.setToolTipText(bundle.getString("CONTAC.FORM.BTNNUEVO")); // NOI18N
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAgregar.setFocusable(false);
        btnAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAgregar.setMaximumSize(new java.awt.Dimension(40, 32));
        btnAgregar.setMinimumSize(new java.awt.Dimension(40, 32));
        btnAgregar.setPreferredSize(new java.awt.Dimension(70, 20));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        tbRegistroInventarios.add(btnAgregar);
        tbRegistroInventarios.add(separatorOne);

        btnEditar.setIcon(new ImageIcon(getClass().getResource("/contac/resources/icons/actions/edit.png")));
        btnEditar.setToolTipText(bundle.getString("CONTAC.FORM.BTNEDITAR")); // NOI18N
        btnEditar.setFocusable(false);
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditar.setMaximumSize(new java.awt.Dimension(40, 32));
        btnEditar.setMinimumSize(new java.awt.Dimension(40, 32));
        btnEditar.setName(""); // NOI18N
        btnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        tbRegistroInventarios.add(btnEditar);
        tbRegistroInventarios.add(separatorTwo);

        btnAnular.setIcon(new ImageIcon(getClass().getResource("/contac/resources/icons/actions/remove2.png")));
        btnAnular.setToolTipText(bundle.getString("CONTAC.FORM.BTNANULAR")); // NOI18N
        btnAnular.setFocusable(false);
        btnAnular.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAnular.setMaximumSize(new java.awt.Dimension(40, 32));
        btnAnular.setMinimumSize(new java.awt.Dimension(40, 32));
        btnAnular.setName(""); // NOI18N
        btnAnular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnularActionPerformed(evt);
            }
        });
        tbRegistroInventarios.add(btnAnular);

        JScrollPane ordenesEntradaScrollbar = new JScrollPane();
        ordenesEntradaScrollbar.getViewport().add(tblOrdenesEntrada);

        pnlRegistroInventario.add(tbRegistroInventarios, BorderLayout.NORTH);
        pnlRegistroInventario.add(ordenesEntradaScrollbar, BorderLayout.CENTER);
        //pnlRegistroInventario.add(tbRegistroInventarios, java.awt.BorderLayout.PAGE_START);

        //*********************************************************************
        //Create Main View
        //*********************************************************************
        this.setLayout(new BorderLayout());

        this.add(header, BorderLayout.NORTH);
        this.add(searchPanel, BorderLayout.WEST);
        this.add(pnlRegistroInventario, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void initValues() {
        try {
            //Init campos de busqueda
        dtpFechaDesde.setFormats("dd/MM/yyyy");
        dtpFechaDesde.setDate(new Date());

        dtpFechaHasta.setFormats("dd/MM/yyyy");
        dtpFechaHasta.setDate(new Date());

        //Config table model para lavantamiento inventario fisico
        ordenEntradaBeanTableModel = new BeanTableModel<OrdenEntrada>(OrdenEntrada.class, OrdenMovimiento.class,
                controller.getOrdenesEntrada());
        ordenEntradaBeanTableModel.setModelEditable(false);
        tblOrdenesEntrada.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        ordenEntradaBeanTableModel.sortColumnNames();
        tblOrdenesEntrada.setEditable(false);
        tblOrdenesEntrada.setModel(ordenEntradaBeanTableModel);
        tblOrdenesEntrada.setRowSelectionAllowed(true);

        //Obteniendo table column model y removiendo columnas innecesarias
        TableColumnModel tableColumnModel = tblOrdenesEntrada.getColumnModel();
        String[] columnsRemove = new String[]{"Persona Entrega", "Tipo Entrada", "Fecha Solicitud", "Id", "Ctime", "Cuser", "Mtime", "Muser"};

        for (String columnLabel : columnsRemove) {
            tableColumnModel.removeColumn(tableColumnModel.getColumn(tableColumnModel.getColumnIndex(columnLabel)));
        }

        //Adding cell rendering claass
        tableColumnModel.getColumn(0).setCellRenderer(new AlmacenFormatRenderer());
        tableColumnModel.getColumn(2).setCellRenderer(new EstadoFormatRenderer());
        tableColumnModel.getColumn(3).setCellRenderer(new FechaFormatRenderer());
        tableColumnModel.getColumn(4).setCellRenderer(new MonedaFormatRenderer());
        DecimalFormatRenderer decimalFormatRenderer = new DecimalFormatRenderer();
        decimalFormatRenderer.setHorizontalAlignment(JLabel.RIGHT);
        tableColumnModel.getColumn(5).setCellRenderer(decimalFormatRenderer);

        //Ordering table columns
        tableColumnModel.moveColumn(6, 0); //No Movimiento
        tableColumnModel.moveColumn(3, 6); //Estado Movimiento

        //Setting prefered size
        tableColumnModel.getColumn(0).setPreferredWidth(15);
        tableColumnModel.getColumn(2).setPreferredWidth(250);

        cmbAlmacen.setModel(new AlmacenComboBoxModel(controller.buscarAlmacenes()));
        ListCellRenderer rendererAlmacen = new ComboBoxEmptySelectionRenderer(cmbAlmacen, messageBundle.getString("CONTAC.FORM.MSG.SELECCIONE"));
        cmbAlmacen.setRenderer(rendererAlmacen);
        cmbAlmacen.setSelectedIndex(-1);

        controller.setAlmacen(null);

        } catch (Exception e) {
            logger.error(e.getMessage(), e);
            JOptionErrorPane.showMessageError(null, messageBundle.getString("CONTAC.FORM.ADMINISTRAPRODUCTO.ERROR.REGISTRO"),
                    e.getMessage());
        }
    }

    private void initActionListeners() {
        btnBuscar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnBuscarActionPerformed(e);
            }
        });
    }
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {

            //Obteniendo fechas de busqueda
            Date fechaDesde = dtpFechaDesde.getDate();
            Date fechaHasta = dtpFechaHasta.getDate();

            //Obtener parametros de busqueda
            Almacen almacen = ((Almacen) ((AlmacenComboBoxModel) cmbAlmacen.getModel()).getSelectedItem().
                    getObject());

            //Consultando listado de Ordenes de Entradas de clientes por fecha
            controller.buscarOrdenesEntradasPorFechasAlmacen(fechaDesde, fechaHasta, almacen.getId());

            //Actualizar listado de articulos ingresados
            ((BeanTableModel) tblOrdenesEntrada.getModel()).fireTableDataChanged();

        } catch (Exception e) {
            //Show error message
            JOptionErrorPane.showMessageWarning(null, messageBundle.getString("CONTAC.FORM.MSG.ERROR"), e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed
    private void tblOrdenesEntradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOrdenesEntradaMouseClicked

        // Getting orden de entrada selected
        rowSelected = tblOrdenesEntrada.getSelectedRow();
        ordenEntradaSelected = (OrdenEntrada) ((BeanTableModel) tblOrdenesEntrada.getModel()).getRow(rowSelected);
        controller.setOrdenEntrada(ordenEntradaSelected);
    }//GEN-LAST:event_tblOrdenesEntradaMouseClicked

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        //Open formulario de administracion de compania
        getMDI().getStyle().addPanel("pnlOrdenSalidaInventario", "contac.inventarios.movimiento.inventario.app.pnlOrdenEntradaInventario");

        //Remove this panel
        getMDI().getStyle().removePanel(this);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

        if (ordenEntradaSelected != null) {
            //Open formulario de ingreso de inventario fisico
            getMDI().getStyle().addPanel("pnlOrdenEntradaInventario", "contac.inventarios.movimiento.inventario.app.pnlOrdenEntradaInventario",
                    controller);

            //Remove this panel
            getMDI().getStyle().removePanel(this);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnAnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnularActionPerformed

        try {

            if (ordenEntradaSelected != null) {

                //Setting orden de entrada selected
                controller.setOrdenEntrada(ordenEntradaSelected);

                boolean confirmation = JOptionMessagePane.showConfirmationInfo(null, messageBundle.getString("CONTAC.FORM.ORDENENTRADA.ADVERTENCIA"), MessageFormat.
                        format(messageBundle.getString("CONTAC.FORM.ORDENENTRADA.ELIMINA.CONFIRMA"),
                                new Object[]{ordenEntradaSelected.getNoMovimiento()}));

                if (confirmation) {
                    //Remover orden de entrada
                    controller.removerOrdenEntrada();

                    //Show confirmation message
                    JOptionErrorPane.showMessageInfo(null, messageBundle.getString("CONTAC.FORM.ORDENENTRADA.ELIMINA.EXITOSO"),
                            messageBundle.getString("CONTAC.FORM.ORDENENTRADA.ELIMINA.EXITOSO"));

                    //Actualizar listado de articulos ingresados
                    ((BeanTableModel) tblOrdenesEntrada.getModel()).fireTableDataChanged();
                }
            }

        } catch (Exception e) {
            logger.error(e.getMessage(), e);
            JOptionErrorPane.showMessageError(null, messageBundle.getString("CONTAC.FORM.ADMINISTRAPRODUCTO.ERROR.REGISTRO"),
                    e.getMessage());
        }
    }//GEN-LAST:event_btnAnularActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAnular;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnBuscar;
    private org.jdesktop.swingx.JXHeader headerAlmacenes;
    private javax.swing.JPanel pnlRegistroInventario;
    private javax.swing.JScrollPane scrollOrdenesEntrada;
    private javax.swing.JToolBar.Separator separatorOne;
    private javax.swing.JToolBar.Separator separatorTwo;
    private javax.swing.JToolBar tbRegistroInventarios;
    private org.jdesktop.swingx.JXTable tblOrdenesEntrada;
    private JScrollPane scrollProformasClientes;
    private JScrollPane scrollProformaWest;
    private javax.swing.JLabel lblAlmacen;
    private javax.swing.JLabel lblFechaDesde;
    private javax.swing.JLabel lblFechaHasta;
    private javax.swing.JComboBox cmbAlmacen;
    private org.jdesktop.swingx.JXDatePicker dtpFechaDesde;
    private org.jdesktop.swingx.JXDatePicker dtpFechaHasta;
    private JPanel pnlRegistroProformasWest;
    // End of variables declaration//GEN-END:variables

    private BeanTableModel<OrdenEntrada> ordenEntradaBeanTableModel;
    private OrdenEntrada ordenEntradaSelected;
    private int rowSelected;
}
