--INSERTAR ACTIVIDADES ECONOMICAS
INSERT INTO GEN_ACTIVIDADECONOMICA (N_ID, C_NOMBRE, C_DESCRIPCION, C_CUSER, D_CTIME, C_MUSER, D_MTIME) VALUES (1, 'BIENES', 'Bienes', 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO GEN_ACTIVIDADECONOMICA (N_ID, C_NOMBRE, C_DESCRIPCION, C_CUSER, D_CTIME, C_MUSER, D_MTIME) VALUES (2, 'CONSULTORIAS', 'Consultorias', 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO GEN_ACTIVIDADECONOMICA (N_ID, C_NOMBRE, C_DESCRIPCION, C_CUSER, D_CTIME, C_MUSER, D_MTIME) VALUES (3, 'OBRAS', 'Obras', 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());
INSERT INTO GEN_ACTIVIDADECONOMICA (N_ID, C_NOMBRE, C_DESCRIPCION, C_CUSER, D_CTIME, C_MUSER, D_MTIME) VALUES (4, 'SERVICIOS', 'Servicios', 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP());

--INSERTAR LINEAS
INSERT INTO INV_LINEA (C_CODIGO, C_NOMBRE, C_DESCRIPCION, D_CTIME, C_CUSER, D_MTIME, C_MUSER)
VALUES ('001', 'BASEBALL & SOFTBALL', 'BASEBALL & SOFTBALL', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN');
INSERT INTO INV_LINEA (C_CODIGO, C_NOMBRE, C_DESCRIPCION, D_CTIME, C_CUSER, D_MTIME, C_MUSER)
VALUES ('002', 'FOOTBALL', 'FOOTBALL', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN');
INSERT INTO INV_LINEA (C_CODIGO, C_NOMBRE, C_DESCRIPCION, D_CTIME, C_CUSER, D_MTIME, C_MUSER)
VALUES ('003', 'BASKETBALL', 'BASKETBALL', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN');
INSERT INTO INV_LINEA (C_CODIGO, C_NOMBRE, C_DESCRIPCION, D_CTIME, C_CUSER, D_MTIME, C_MUSER)
VALUES ('004', 'VOLLEYBALL', 'VOLLEYBALL', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN');
INSERT INTO INV_LINEA (C_CODIGO, C_NOMBRE, C_DESCRIPCION, D_CTIME, C_CUSER, D_MTIME, C_MUSER)
VALUES ('005', 'DEPORTES ACUATICOS', 'DEPORTES ACUATICOS', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN');
INSERT INTO INV_LINEA (C_CODIGO, C_NOMBRE, C_DESCRIPCION, D_CTIME, C_CUSER, D_MTIME, C_MUSER)
VALUES ('006', 'CAZA Y PESCA', 'CAZA Y PESCA', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN');
INSERT INTO INV_LINEA (C_CODIGO, C_NOMBRE, C_DESCRIPCION, D_CTIME, C_CUSER, D_MTIME, C_MUSER)
VALUES ('007', 'BUCEO DEPORTIVO', 'BUCEO DEPORTIVO', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN');
INSERT INTO INV_LINEA (C_CODIGO, C_NOMBRE, C_DESCRIPCION, D_CTIME, C_CUSER, D_MTIME, C_MUSER)
VALUES ('008', 'TENNIS CAMPO', 'TENNIS CAMPO', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN');
INSERT INTO INV_LINEA (C_CODIGO, C_NOMBRE, C_DESCRIPCION, D_CTIME, C_CUSER, D_MTIME, C_MUSER)
VALUES ('009', 'TENNIS DE MESA', 'TENNIS DE MESA', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN');
INSERT INTO INV_LINEA (C_CODIGO, C_NOMBRE, C_DESCRIPCION, D_CTIME, C_CUSER, D_MTIME, C_MUSER)
VALUES ('010', 'DEPORTES DE MESA', 'DEPORTES DE MESA', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN');
INSERT INTO INV_LINEA (C_CODIGO, C_NOMBRE, C_DESCRIPCION, D_CTIME, C_CUSER, D_MTIME, C_MUSER)
VALUES ('011', 'ARTICULOS RECREATIVOS', 'ARTICULOS RECREATIVOS', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN');
INSERT INTO INV_LINEA (C_CODIGO, C_NOMBRE, C_DESCRIPCION, D_CTIME, C_CUSER, D_MTIME, C_MUSER)
VALUES ('012', 'LIBROS & REVISTAS', 'LIBROS & REVISTAS', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN');
INSERT INTO INV_LINEA (C_CODIGO, C_NOMBRE, C_DESCRIPCION, D_CTIME, C_CUSER, D_MTIME, C_MUSER)
VALUES ('013', 'TROFEOS Y MEDALLAS', 'TROFEOS Y MEDALLAS', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN');
INSERT INTO INV_LINEA (C_CODIGO, C_NOMBRE, C_DESCRIPCION, D_CTIME, C_CUSER, D_MTIME, C_MUSER)
VALUES ('014', 'ROPA DEPORTIVA', 'ROPA DEPORTIVA', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN');
INSERT INTO INV_LINEA (C_CODIGO, C_NOMBRE, C_DESCRIPCION, D_CTIME, C_CUSER, D_MTIME, C_MUSER)
VALUES ('015', 'DEPORTES EXTREMOS & CAMPO', 'DEPORTES EXTREMOS & CAMPO', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN');
INSERT INTO INV_LINEA (C_CODIGO, C_NOMBRE, C_DESCRIPCION, D_CTIME, C_CUSER, D_MTIME, C_MUSER)
VALUES ('016', 'BILLIARD', 'BILLIARD', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN');
INSERT INTO INV_LINEA (C_CODIGO, C_NOMBRE, C_DESCRIPCION, D_CTIME, C_CUSER, D_MTIME, C_MUSER)
VALUES ('017', 'CALZADO DEPORTIVO', 'CALZADO DEPORTIVO', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN');
INSERT INTO INV_LINEA (C_CODIGO, C_NOMBRE, C_DESCRIPCION, D_CTIME, C_CUSER, D_MTIME, C_MUSER)
VALUES ('019', 'DEPORTES DE COMBATE', 'DEPORTES DE COMBATE', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN');
INSERT INTO INV_LINEA (C_CODIGO, C_NOMBRE, C_DESCRIPCION, D_CTIME, C_CUSER, D_MTIME, C_MUSER)
VALUES ('020', 'FITNESS Y MAQUINAS PARA EJERCICIO', 'FITNESS Y MAQUINAS PARA EJERCICIO', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN');
INSERT INTO INV_LINEA (C_CODIGO, C_NOMBRE, C_DESCRIPCION, D_CTIME, C_CUSER, D_MTIME, C_MUSER)
VALUES ('029', 'ATLETISMO', 'ATLETISMO', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN');
INSERT INTO INV_LINEA (C_CODIGO, C_NOMBRE, C_DESCRIPCION, D_CTIME, C_CUSER, D_MTIME, C_MUSER)
VALUES ('030', 'VARIOS', 'VARIOS', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN');

--INSERTAR ESTADOS PRODUCTOS
INSERT INTO INV_ESTADO_PRODUCTO(C_NOMBRE, C_DESCRIPCION, C_ALIAS, D_CTIME, C_CUSER, D_MTIME, C_MUSER)
VALUES('INGRESADO', 'INGRESADO', 'INGRESADO', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN');
INSERT INTO INV_ESTADO_PRODUCTO(C_NOMBRE, C_DESCRIPCION, C_ALIAS, D_CTIME, C_CUSER, D_MTIME, C_MUSER)
VALUES('VIGENTE', 'VIGENTE', 'VIGENTE', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN');
INSERT INTO INV_ESTADO_PRODUCTO(C_NOMBRE, C_DESCRIPCION, C_ALIAS, D_CTIME, C_CUSER, D_MTIME, C_MUSER)
VALUES('CERRADO', 'CERRADO', 'CERRADO', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN');
INSERT INTO INV_ESTADO_PRODUCTO(C_NOMBRE, C_DESCRIPCION, C_ALIAS, D_CTIME, C_CUSER, D_MTIME, C_MUSER)
VALUES('LIQUIDACION', 'LIQUIDACION', 'LIQUIDACION', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN');
INSERT INTO INV_ESTADO_PRODUCTO(C_NOMBRE, C_DESCRIPCION, C_ALIAS, D_CTIME, C_CUSER, D_MTIME, C_MUSER)
VALUES('OFERTA', 'OFERTA', 'OFERTA', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN');
INSERT INTO INV_ESTADO_PRODUCTO(C_NOMBRE, C_DESCRIPCION, C_ALIAS, D_CTIME, C_CUSER, D_MTIME, C_MUSER)
VALUES('DEBAJA', 'DEBAJA', 'DEBAJA', CURRENT_TIMESTAMP(), 'SYSADMIN', CURRENT_TIMESTAMP(), 'SYSADMIN');