/**
 * Copyright 2012 Contac Business Software. All rights reserved.
 * CONTAC PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */

/*
 * pnlBusquedaCliente.java
 *
 * Created on 02-07-2012, 10:51:28 PM
 */
package contac.commons.components;

import contac.commons.app.BusquedaClienteController;
import contac.commons.form.label.JOptionErrorPane;
import contac.commons.form.panel.GenericFrame;
import contac.commons.models.tables.BeanTableModel;
import contac.internationalization.LanguageLocale;
import contac.modelo.entity.Cliente;
import org.apache.log4j.Logger;

import javax.swing.*;
import javax.swing.table.TableColumnModel;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ResourceBundle;

/**
 * @author EMontenegro
 */
public class pnlBusquedaCliente extends JDialog {

    //Apache log4j
    private static final Logger logger = Logger.getLogger(pnlBusquedaProveedor.class);

    //Message resource bundle
    private ResourceBundle messageBundle = ResourceBundle.getBundle("contac/commons/components/mensajes/Mensajes",
            LanguageLocale.getInstance().getLocale());

    //Controller
    private BusquedaClienteController controller;

    /**
     * Creates new form pnlBusquedaCliente
     */
    public pnlBusquedaCliente(GenericFrame frame, boolean modal) {

        //Constructor
        super(frame, modal);

        //Controller
        controller = new BusquedaClienteController();

        //Init components
        initComponents();

        //Init clientes components
        initClientesComponents();

        //Set visible
        setTitle(messageBundle.getString("CONTAC.FORM.BUSQUEDACLIENTEPNL.TITULO"));
        this.setLocation(400, 300);
        this.setSize(new Dimension(650, 400));
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleHeader = new org.jdesktop.swingx.JXHeader();
        frmBusqueda = new javax.swing.JPanel();
        pnlParametros = new javax.swing.JPanel();
        lblRazonSocial = new javax.swing.JLabel();
        txtRazonSocial = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        txtNit = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        tblClientes = new org.jdesktop.swingx.JXTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titleHeader.setBackground(new java.awt.Color(204, 204, 204));
        titleHeader.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        titleHeader.setMinimumSize(new java.awt.Dimension(160, 42));
        titleHeader.setPreferredSize(new java.awt.Dimension(51, 40));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("contac/commons/components/mensajes/Mensajes_es"); // NOI18N
        titleHeader.setTitle(bundle.getString("CONTAC.FORM.BUSQUEDACLIENTEPNL.TITULO")); // NOI18N
        titleHeader.setTitleForeground(new java.awt.Color(255, 153, 0));
        getContentPane().add(titleHeader, java.awt.BorderLayout.NORTH);

        frmBusqueda.setPreferredSize(new java.awt.Dimension(679, 100));
        frmBusqueda.setLayout(new java.awt.BorderLayout());

        pnlParametros.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlParametros.setPreferredSize(new java.awt.Dimension(788, 75));

        lblRazonSocial.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRazonSocial.setText(bundle.getString("CONTAC.FORM.BUSQUEDAPROVEEDORPNL.RAZONSOCIAL")); // NOI18N

        txtRazonSocial.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtRazonSocial.setToolTipText("");
        txtRazonSocial.setMinimumSize(new java.awt.Dimension(6, 25));
        txtRazonSocial.setPreferredSize(new java.awt.Dimension(59, 30));

        btnBuscar.setText(bundle.getString("CONTAC.FORM.BTNBUSCAR")); // NOI18N
        btnBuscar.setActionCommand("");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        txtNit.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNit.setToolTipText("");
        txtNit.setMinimumSize(new java.awt.Dimension(6, 25));
        txtNit.setPreferredSize(new java.awt.Dimension(59, 30));

        lblCodigo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCodigo.setText(bundle.getString("CONTAC.FORM.BUSQUEDACLIENTEPNL.NIT")); // NOI18N

        javax.swing.GroupLayout pnlParametrosLayout = new javax.swing.GroupLayout(pnlParametros);
        pnlParametros.setLayout(pnlParametrosLayout);
        pnlParametrosLayout.setHorizontalGroup(
            pnlParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlParametrosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(pnlParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNit, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(pnlParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlParametrosLayout.createSequentialGroup()
                                    .addComponent(txtRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblRazonSocial))
                    .addGap(235, 235, 235))
        );
        pnlParametrosLayout.setVerticalGroup(
            pnlParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlParametrosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(pnlParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(pnlParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        frmBusqueda.add(pnlParametros, java.awt.BorderLayout.PAGE_START);

        tblClientes.setEditable(false);
        jScrollPane.setViewportView(tblClientes);

        frmBusqueda.add(jScrollPane, java.awt.BorderLayout.CENTER);

        getContentPane().add(frmBusqueda, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initClientesComponents() {

        //Configurando listado de clientes
        clienteBeanTableModel = new BeanTableModel<Cliente>(Cliente.class, controller.getClientes());
        clienteBeanTableModel.setModelEditable(false);
        clienteBeanTableModel.sortColumnNames();
        tblClientes.setModel(clienteBeanTableModel);
        tblClientes.setRowSelectionAllowed(true);

        //Getting table column model and remove innecessary columns
        TableColumnModel columnModel = tblClientes.getColumnModel();

        String[] clienteColumnRemove = new String[]{"Id", "Actividad Economica", "Direccion", "Plazo Credito",
                "Limite Credito", "Descuento", "Cuenta", "Tipo Persona", "Estatus", "Ctime", "Cuser", "Mtime", "Muser"};

        for (String columnLabel : clienteColumnRemove) {
            columnModel.removeColumn(columnModel.getColumn(columnModel.getColumnIndex(columnLabel)));
        }

        //Setting prefered sized
        columnModel.getColumn(0).setPreferredWidth(15);
        columnModel.getColumn(1).setPreferredWidth(20);

        //Adding listener table clientes
        tblClientes.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    //Getting producto selected
                    rowSelected = tblClientes.getSelectedRow();
                    clienteSelected = (Cliente) ((BeanTableModel) tblClientes.getModel()).getRow(rowSelected);

                    //Close JDialog
                    dispose();
                }
            }
        });

    }

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        try {

            //Setting campos de busqueda
            if (!txtNit.getText().equals("")) {
                controller.setNit(txtNit.getText());
            }
            controller.setRazonSocial(txtRazonSocial.getText());

            //Buscar clientes
            controller.buscarClientes();

            //Renderizar tabla de detalle de clientes
            ((BeanTableModel) tblClientes.getModel()).fireTableDataChanged();

        } catch (Exception e) {
            logger.error(e.getMessage(), e);
            JOptionErrorPane.showMessageError(null, e.getMessage(), e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    //RETURN: return cliente selected
    public Cliente getClienteSelected() {
        return clienteSelected;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JPanel frmBusqueda;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblRazonSocial;
    private javax.swing.JPanel pnlParametros;
    private org.jdesktop.swingx.JXTable tblClientes;
    private org.jdesktop.swingx.JXHeader titleHeader;
    private javax.swing.JTextField txtNit;
    private javax.swing.JTextField txtRazonSocial;
    // End of variables declaration//GEN-END:variables

    private BeanTableModel<Cliente> clienteBeanTableModel;
    private Cliente clienteSelected;
    private int rowSelected;
}
