/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * pnlBusquedaProveedor.java
 *
 * Created on 10-31-2011, 10:37:47 PM
 */
package contac.commons.components;


import contac.commons.app.BusquedaProveedorController;
import contac.commons.form.label.JOptionErrorPane;
import contac.commons.form.panel.GenericFrame;
import contac.commons.form.render.DecimalFormatRenderer;
import contac.commons.models.tables.BeanTableModel;
import contac.internationalization.LanguageLocale;
import contac.modelo.entity.Proveedor;
import org.apache.log4j.Logger;

import javax.swing.table.TableColumnModel;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ResourceBundle;

/**
 * @author EMontenegro
 */
public class pnlBusquedaProveedor extends javax.swing.JDialog {

    //Apache log4j
    private static final Logger logger = Logger.getLogger(pnlBusquedaProveedor.class);

    //Message resource bundle
    private ResourceBundle messageBundle = ResourceBundle.getBundle("contac/commons/components/mensajes/Mensajes",
            LanguageLocale.getInstance().getLocale());

    //Controller
    private BusquedaProveedorController controller;

    /**
     * Creates new form pnlBusquedaProveedor
     */
    public pnlBusquedaProveedor(GenericFrame frame, boolean modal) {

        //Constructor
        super(frame, modal);

        //Controller
        controller = new BusquedaProveedorController();

        //Init components
        initComponents();

        //Init proveedores components
        initProveedoresComponents();

        //Set visible
        setTitle(messageBundle.getString("CONTAC.FORM.BUSQUEDAPROVEEDORPNL.TITULO"));
        this.setLocation(400, 300);
        this.setSize(new Dimension(600, 400));
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleHeader = new org.jdesktop.swingx.JXHeader();
        frmBusqueda = new javax.swing.JPanel();
        pnlParametros = new javax.swing.JPanel();
        lblRazonSocial = new javax.swing.JLabel();
        txtRazonSocial = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        tblProveedores = new org.jdesktop.swingx.JXTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titleHeader.setBackground(new java.awt.Color(204, 204, 204));
        titleHeader.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        titleHeader.setPreferredSize(new java.awt.Dimension(51, 40));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("contac/commons/components/mensajes/Mensajes_es"); // NOI18N
        titleHeader.setTitle(bundle.getString("CONTAC.FORM.BUSQUEDAPROVEEDORPNL.TITULO")); // NOI18N
        titleHeader.setTitleForeground(new java.awt.Color(255, 153, 0));
        getContentPane().add(titleHeader, java.awt.BorderLayout.NORTH);

        frmBusqueda.setMinimumSize(new java.awt.Dimension(200, 100));
        frmBusqueda.setPreferredSize(new java.awt.Dimension(679, 100));
        frmBusqueda.setLayout(new java.awt.BorderLayout());

        pnlParametros.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblRazonSocial.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRazonSocial.setText(bundle.getString("CONTAC.FORM.BUSQUEDAPROVEEDORPNL.RAZONSOCIAL")); // NOI18N

        txtRazonSocial.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtRazonSocial.setToolTipText("");
        txtRazonSocial.setMinimumSize(new java.awt.Dimension(6, 25));
        txtRazonSocial.setPreferredSize(new java.awt.Dimension(59, 30));

        btnBuscar.setText(bundle.getString("CONTAC.FORM.BTNBUSCAR")); // NOI18N
        btnBuscar.setActionCommand("");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        txtCodigo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCodigo.setToolTipText("");
        txtCodigo.setMinimumSize(new java.awt.Dimension(6, 25));
        txtCodigo.setPreferredSize(new java.awt.Dimension(59, 30));

        lblCodigo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCodigo.setText(bundle.getString("CONTAC.FORM.BUSQUEDAPRODUCTOPNL.CODIGO")); // NOI18N

        javax.swing.GroupLayout pnlParametrosLayout = new javax.swing.GroupLayout(pnlParametros);
        pnlParametros.setLayout(pnlParametrosLayout);
        pnlParametrosLayout.setHorizontalGroup(
            pnlParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlParametrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRazonSocial)
                    .addComponent(txtRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(239, 239, 239))
        );
        pnlParametrosLayout.setVerticalGroup(
            pnlParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlParametrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnBuscar.getAccessibleContext().setAccessibleName("");

        frmBusqueda.add(pnlParametros, java.awt.BorderLayout.PAGE_START);

        tblProveedores.setEditable(false);
        jScrollPane.setViewportView(tblProveedores);

        frmBusqueda.add(jScrollPane, java.awt.BorderLayout.CENTER);

        getContentPane().add(frmBusqueda, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void initProveedoresComponents() {

        //Configurando listado de proveedores
        proveedorBeanTableModel = new BeanTableModel<Proveedor>(Proveedor.class, controller.getProveedores());
        proveedorBeanTableModel.setModelEditable(false);
        tblProveedores.setModel(proveedorBeanTableModel);
        tblProveedores.setRowSelectionAllowed(true);

        //Obteniendo table column model y removiendo columnas innecesarias
        TableColumnModel proveedorColumnModel = tblProveedores.getColumnModel();

        String[] proveedorColumnRemove = new String[]{"Id", "Cuenta", "Descuento", "Plazo Credito", "Limite Credito",
                "Tipo Persona", "Actividad Economica", "Direccion", "Estatus", "Ctime", "Cuser", "Mtime", "Muser"};

        for (String columnLabel :proveedorColumnRemove) {
            proveedorColumnModel.removeColumn(proveedorColumnModel.getColumn(proveedorColumnModel.getColumnIndex(columnLabel)));
        }

        //Adding listener table proveedores
        tblProveedores.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    //Getting proveedores selected
                    rowSelected = tblProveedores.getSelectedRow();
                    proveedorSelected = (Proveedor) ((BeanTableModel) tblProveedores.getModel()).getRow(rowSelected);

                    //Close JDialog
                    dispose();
                }
            }
        });
    }

    /**
     * Retorna producto seleccionado
     *
     * @return Producto
     */
    public Proveedor getProveedorSelected() {
        return proveedorSelected;
    }

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        try {

            //Setting campos de busqueda
            if (!txtCodigo.getText().equals("")) {
                controller.setCodigo(Long.parseLong(txtCodigo.getText()));
            }
            controller.setRazonSocial(txtRazonSocial.getText());

            //Buscar productos
            controller.buscarProveedores();

            //Renderizar tabla de detalle de productos
            ((BeanTableModel) tblProveedores.getModel()).fireTableDataChanged();

        } catch (Exception e) {
            logger.error(e.getMessage(), e);
            JOptionErrorPane.showMessageError(null, e.getMessage(), e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JPanel frmBusqueda;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblRazonSocial;
    private javax.swing.JPanel pnlParametros;
    private org.jdesktop.swingx.JXTable tblProveedores;
    private org.jdesktop.swingx.JXHeader titleHeader;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtRazonSocial;
    // End of variables declaration//GEN-END:variables

    private BeanTableModel<Proveedor> proveedorBeanTableModel;
    private Proveedor proveedorSelected;
    private int rowSelected;
}
