/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * pnlRegistroCompanias.java
 *
 * Created on Jul 5, 2011, 10:43:53 AM
 */
package contac.administracion.compania.app;

import contac.administracion.controller.AdministraCompaniaController;
import contac.commons.form.panel.GenericFrame;
import contac.commons.form.panel.GenericPanel;
import contac.commons.models.tables.BeanTableModel;
import contac.modelo.entity.Almacen;
import contac.modelo.entity.Compania;

import javax.swing.*;
import javax.swing.table.TableColumnModel;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

/**
 * @author Eddy
 */
public class pnlRegistroCompanias extends GenericPanel {

    //Message resource bundle
    private static final String messageBundleUrl = "contac.servicio.app.mensajes.Mensajes";

    //Controller
    private AdministraCompaniaController controller;

    /**
     * Constructor
     *
     * @param frame, GenericFrame
     */
    public pnlRegistroCompanias(GenericFrame frame) {

        //Call super constructor
        super(frame, "registroCompanias", "Administrar Compa\u00f1\u00eda", true, messageBundleUrl,
                new Locale("es", "NIC"));

        //Init controller
        controller = new AdministraCompaniaController();

        //Init components
        initComponents();

        //Setting table model
        initValues();
    }

    @Override
    public void initValues() {

        //Config table model para companias
        companiaBeanTableModel = new BeanTableModel<Compania>(Compania.class, controller.getCompanias());
        companiaBeanTableModel.setModelEditable(false);
        //companiaBeanTableModel.sortColumnNames();
        tblCompanias.setModel(companiaBeanTableModel);
        tblCompanias.setRowSelectionAllowed(true);

        //Obteniendo table column model y removiendo columnas innecesarias
        TableColumnModel tableColumnModel = tblCompanias.getColumnModel();
        String[] columnsRemove = new String[]{"Id", "Fecha Constitucion", "Fecha Alta Contribuyente", "Eslogan", "Direccion",
                "Moneda Referencia", "Tipo Persona", "Estatus", "Logotipo", "Ctime", "Cuser", "Mtime", "Muser"};

        for (String columnLabel : columnsRemove) {
            tableColumnModel.removeColumn(tableColumnModel.getColumn(tableColumnModel.getColumnIndex(columnLabel)));
        }
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRegistroCompanias = new javax.swing.JPanel();
        scrollCompania = new javax.swing.JScrollPane();
        tblCompanias = new javax.swing.JTable();
        tbCompanias = new javax.swing.JToolBar();
        btnAgregarCompania = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnEditarCompania = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnRemoverCompania = new javax.swing.JButton();
        headerAlmacenes = new org.jdesktop.swingx.JXHeader();

        setLayout(new java.awt.BorderLayout());

        pnlRegistroCompanias.setLayout(new java.awt.BorderLayout());

        scrollCompania.setPreferredSize(new java.awt.Dimension(452, 420));

        tblCompanias.setMinimumSize(new java.awt.Dimension(60, 90));
        tblCompanias.setPreferredSize(new java.awt.Dimension(300, 60));
        tblCompanias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCompaniasMouseClicked(evt);
            }
        });
        scrollCompania.setViewportView(tblCompanias);

        pnlRegistroCompanias.add(scrollCompania, java.awt.BorderLayout.CENTER);

        tbCompanias.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tbCompanias.setMaximumSize(new java.awt.Dimension(124, 32));
        tbCompanias.setMinimumSize(new java.awt.Dimension(124, 32));
        tbCompanias.setPreferredSize(new java.awt.Dimension(124, 32));

        btnAgregarCompania.setIcon(new ImageIcon(getClass().getResource("/contac/resources/icons/actions/new.png")));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("contac/administracion/app/mensajes/Mensajes_es"); // NOI18N
        btnAgregarCompania.setToolTipText(bundle.getString("CONTAC.FORM.BTNNUEVO")); // NOI18N
        btnAgregarCompania.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAgregarCompania.setFocusable(false);
        btnAgregarCompania.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAgregarCompania.setMaximumSize(new java.awt.Dimension(40, 32));
        btnAgregarCompania.setMinimumSize(new java.awt.Dimension(40, 32));
        btnAgregarCompania.setPreferredSize(new java.awt.Dimension(70, 20));
        btnAgregarCompania.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCompaniaActionPerformed(evt);
            }
        });
        tbCompanias.add(btnAgregarCompania);
        tbCompanias.add(jSeparator1);

        btnEditarCompania.setIcon(new ImageIcon(getClass().getResource("/contac/resources/icons/actions/edit.png")));
        btnEditarCompania.setToolTipText(bundle.getString("CONTAC.FORM.BTNEDITAR")); // NOI18N
        btnEditarCompania.setFocusable(false);
        btnEditarCompania.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditarCompania.setMaximumSize(new java.awt.Dimension(40, 32));
        btnEditarCompania.setMinimumSize(new java.awt.Dimension(40, 32));
        btnEditarCompania.setName(""); // NOI18N
        btnEditarCompania.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditarCompania.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarCompaniaActionPerformed(evt);
            }
        });
        tbCompanias.add(btnEditarCompania);
        tbCompanias.add(jSeparator2);

        btnRemoverCompania.setIcon(new ImageIcon(getClass().getResource("/contac/resources/icons/actions/remove2.png")));
        btnRemoverCompania.setToolTipText(bundle.getString("CONTAC.FORM.BTNELIMINAR")); // NOI18N
        btnRemoverCompania.setFocusable(false);
        btnRemoverCompania.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnRemoverCompania.setMaximumSize(new java.awt.Dimension(40, 32));
        btnRemoverCompania.setMinimumSize(new java.awt.Dimension(40, 32));
        btnRemoverCompania.setName(""); // NOI18N
        tbCompanias.add(btnRemoverCompania);

        pnlRegistroCompanias.add(tbCompanias, java.awt.BorderLayout.PAGE_START);

        add(pnlRegistroCompanias, java.awt.BorderLayout.CENTER);

        headerAlmacenes.setForeground(new java.awt.Color(255, 153, 0));
        headerAlmacenes.setPreferredSize(new java.awt.Dimension(51, 35));
        headerAlmacenes.setTitle(bundle.getString("CONTAC.FORM.ADMINISTRACOMPANIA")); // NOI18N
        headerAlmacenes.setTitleForeground(new java.awt.Color(255, 153, 0));
        add(headerAlmacenes, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents

     //<Accion de agregar un nuevo registro de compania>
    private void btnAgregarCompaniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCompaniaActionPerformed
        //Open formulario de administracion de compania
        getMDI().getStyle().addPanel("pnlAdmonCompania", "contac.administracion.compania.app.pnlAdmonCompania");

        //Remove this panel
        getMDI().getStyle().removePanel(this);

    }//GEN-LAST:event_btnAgregarCompaniaActionPerformed

    private void tblCompaniasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCompaniasMouseClicked

        //Getting compania selected
        rowSelected = tblCompanias.getSelectedRow();
        companiaSelected = (Compania) ((BeanTableModel) tblCompanias.getModel()).getRow(rowSelected);
        controller.setCompania(companiaSelected);

    }//GEN-LAST:event_tblCompaniasMouseClicked

    private void btnEditarCompaniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCompaniaActionPerformed

        if (companiaSelected != null) {
            //Open formulario de administracion de compania
            getMDI().getStyle().addPanel("pnlAdmonCompania", "contac.administracion.compania.app.pnlAdmonCompania", controller);

            //Remove this panel
            getMDI().getStyle().removePanel(this);
        }
    }//GEN-LAST:event_btnEditarCompaniaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCompania;
    private javax.swing.JButton btnEditarCompania;
    private javax.swing.JButton btnRemoverCompania;
    private org.jdesktop.swingx.JXHeader headerAlmacenes;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JPanel pnlRegistroCompanias;
    private javax.swing.JScrollPane scrollCompania;
    private javax.swing.JToolBar tbCompanias;
    private javax.swing.JTable tblCompanias;
    // End of variables declaration//GEN-END:variables

    private BeanTableModel<Compania> companiaBeanTableModel;
    private BeanTableModel<Almacen> almacenBeanTableModel;
    private Compania companiaSelected;
    private int rowSelected;
}
