/*
 * dlg_RegistrarTasasCambio.java
 *
 * Created on 19 de noviembre de 2008, 09:10 AM
 */
package contac.servicio.app.dialog;

import contac.commons.form.panel.GenericFrame;
import contac.servicio.app.util.Util;

/**
 *
 * @author  hmurbina
 */
public class dlgTasasCambio extends javax.swing.JDialog {

    private GenericFrame mdi;
    Integer ModoEdicion;
    String moneda, fuente, mes, anio;

    /** Creates new form dlg_RegistrarTasasCambio */
    public dlgTasasCambio(GenericFrame mdi, boolean modal) {
        super(mdi, modal);
        this.mdi = mdi;
        initComponents();
        Util u = new Util();
        u.paintTable(this.tblTasa);
        System.gc();
    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXHeader1 = new org.jdesktop.swingx.JXHeader();
        pnlCentral = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lbl1 = new javax.swing.JLabel();
        cmbMoneda = new javax.swing.JComboBox();
        lbl2 = new javax.swing.JLabel();
        cmbFuente = new javax.swing.JComboBox();
        lbl3 = new javax.swing.JLabel();
        mtcMes = new com.toedter.calendar.JMonthChooser();
        lbl4 = new javax.swing.JLabel();
        yrcAnio = new com.toedter.calendar.JYearChooser();
        scrllTasa = new javax.swing.JScrollPane();
        tblTasa = new javax.swing.JTable();
        pnlBoton = new javax.swing.JPanel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tasas de Cambio -  CBA Inventory");
        setMinimumSize(new java.awt.Dimension(518, 469));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jXHeader1.setDescription("");
        jXHeader1.setTitle("Registro de Tasas de Cambio");
        jXHeader1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jXHeader1.setPreferredSize(new java.awt.Dimension(791, 40));
        getContentPane().add(jXHeader1, java.awt.BorderLayout.NORTH);

        pnlCentral.setLayout(new java.awt.BorderLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(100, 60));

        lbl1.setText("Tasa de cambio del cordoba con respecto al");
        jPanel1.add(lbl1);

        cmbMoneda.setPreferredSize(new java.awt.Dimension(130, 20));
        jPanel1.add(cmbMoneda);

        lbl2.setText("según");
        jPanel1.add(lbl2);

        cmbFuente.setPreferredSize(new java.awt.Dimension(130, 20));
        jPanel1.add(cmbFuente);

        lbl3.setText("para el mes de");
        jPanel1.add(lbl3);
        jPanel1.add(mtcMes);

        lbl4.setText("del año");
        jPanel1.add(lbl4);
        jPanel1.add(yrcAnio);

        pnlCentral.add(jPanel1, java.awt.BorderLayout.NORTH);

        tblTasa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Valor (C$)"
            }
        ) {
            Class[] types = new Class [] {
                Object.class, Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTasa.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrllTasa.setViewportView(tblTasa);

        pnlCentral.add(scrllTasa, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlCentral, java.awt.BorderLayout.CENTER);

        pnlBoton.setPreferredSize(new java.awt.Dimension(100, 40));
        pnlBoton.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/button_okx16.png"))); // NOI18N
        btnAceptar.setText("Aceptar");
        pnlBoton.add(btnAceptar);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/button_cancelx16.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnlBoton.add(btnCancelar);

        getContentPane().add(pnlBoton, java.awt.BorderLayout.SOUTH);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-534)/2, (screenSize.height-469)/2, 534, 469);
    }// </editor-fold>//GEN-END:initComponents

private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
    dispose();
    System.gc();
}//GEN-LAST:event_btnCancelarActionPerformed

private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

}//GEN-LAST:event_formWindowOpened
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox cmbFuente;
    private javax.swing.JComboBox cmbMoneda;
    private javax.swing.JPanel jPanel1;
    private org.jdesktop.swingx.JXHeader jXHeader1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private com.toedter.calendar.JMonthChooser mtcMes;
    private javax.swing.JPanel pnlBoton;
    private javax.swing.JPanel pnlCentral;
    private javax.swing.JScrollPane scrllTasa;
    private javax.swing.JTable tblTasa;
    private com.toedter.calendar.JYearChooser yrcAnio;
    // End of variables declaration//GEN-END:variables
}
