/**
 * Copyright 2012 Contac Business Software. All rights reserved.
 * CONTAC PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */

/*
 * AgentesVentasPnl.java
 *
 * Created on 10-03-2012, 10:45:29 AM
 */
package contac.commons.components;

import contac.commons.app.BusquedaAgentesVentasController;
import contac.commons.form.label.JOptionErrorPane;
import contac.commons.form.panel.GenericFrame;
import contac.internationalization.LanguageLocale;
import contac.modelo.entity.AgenteVentas;
import org.apache.log4j.Logger;

import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ResourceBundle;

/**
 * @author emortiz
 */
public class AgentesVentasPnl extends JDialog {

    //Apache log4j
    private static final Logger logger = Logger.getLogger(AgentesVentasPnl.class);

    //Message resource bundle
    private ResourceBundle messageBundle = ResourceBundle.getBundle("contac/commons/components/mensajes/Mensajes",
            LanguageLocale.getInstance().getLocale());

    //Controller
    private BusquedaAgentesVentasController controller;

    /**
     * Creates new form AgentesVentasPnl
     */
    public AgentesVentasPnl(GenericFrame frame, boolean modal) {

        //Constructor
        super(frame, modal);

        try {

            //Controller
            controller = new BusquedaAgentesVentasController();

            //Init components
            initComponents();

            //Init components values
            initComponentsValues();

            //Register listeners
            registerListeners();

            //Set visible
            this.setTitle(messageBundle.getString("CONTAC.FORM.AGENTESVENTASPNL.TITULO"));
            this.setLocation(400, 300);
            this.setSize(new Dimension(200, 300));
            this.setVisible(true);

        } catch (Exception e) {
            logger.error(e.getMessage(), e);
            //Show error message
            JOptionErrorPane.showMessageError(null, messageBundle.getString("CONTAC.FORM.ERROR.INICIO"),
                    e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleHeader = new org.jdesktop.swingx.JXHeader();
        scrollBar = new javax.swing.JScrollPane();
        agentesVentasLst = new javax.swing.JList();

        titleHeader.setBackground(new java.awt.Color(204, 204, 204));
        titleHeader.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        titleHeader.setPreferredSize(new java.awt.Dimension(51, 40));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("contac/commons/components/mensajes/Mensajes_es"); // NOI18N
        titleHeader.setTitle(bundle.getString("CONTAC.FORM.AGENTESVENTASPNL.TITULO")); // NOI18N
        titleHeader.setTitleForeground(new java.awt.Color(255, 153, 0));
        getContentPane().add(titleHeader, java.awt.BorderLayout.PAGE_START);

        scrollBar.setViewportView(agentesVentasLst);

        getContentPane().add(scrollBar, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This method is called from within the constructor to
     * initialize the form datas.
     */
    private void initComponentsValues() {

        //Instantiation of ListModel object for JList
        DefaultListModel listModel = new DefaultListModel();

        //Setting agentes de ventas List
        for (AgenteVentas agente : controller.getAgentesVentas()) {
            listModel.addElement(agente);
        }

        agentesVentasLst.setModel(listModel);
        agentesVentasLst.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        agentesVentasLst.setLayoutOrientation(JList.HORIZONTAL_WRAP);
        agentesVentasLst.setVisibleRowCount(-1);
    }

    /**
     * Register listeners values
     */
    private void registerListeners() {

        this.agentesVentasLst.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    agenteVentasSelected = (AgenteVentas)agentesVentasLst.getSelectedValue();

                    //Close JDialog
                    dispose();
                }
            }
        });

        this.agentesVentasLst.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {

                //Getting SUType selected and setting in state change
                agenteVentasSelected = (AgenteVentas) agentesVentasLst.getSelectedValue();
            }
        });
    }

    /**
     * Return agente de ventas seleccionado
     *
     * @return AgenteVentas
     */
    public AgenteVentas getAgenteVentasSelected() {
        return agenteVentasSelected;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList agentesVentasLst;
    private javax.swing.JScrollPane scrollBar;
    private org.jdesktop.swingx.JXHeader titleHeader;
    // End of variables declaration//GEN-END:variables

    private AgenteVentas agenteVentasSelected;
}
