/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BuscarProductoPnl.java
 *
 * Created on 20-sep-2011, 0:41:58
 */
package contac.commons.components;

import contac.commons.app.BusquedaProductoController;
import contac.commons.form.label.JOptionErrorPane;
import contac.commons.form.panel.GenericFrame;
import contac.commons.form.render.DecimalFormatRenderer;
import contac.commons.models.tables.BeanTableModel;
import contac.internationalization.LanguageLocale;
import contac.modelo.entity.Producto;
import org.apache.log4j.Logger;

import javax.swing.*;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.DecimalFormat;
import java.util.ResourceBundle;

/**
 *
 * @author Eddy Montenegro
 */
public class pnlBusquedaProducto extends JDialog {

    //Apache log4j
    private static final Logger logger = Logger.getLogger(pnlBusquedaProducto.class);

    //Message resource bundle
    private ResourceBundle messageBundle = ResourceBundle.getBundle("contac/commons/components/mensajes/Mensajes",
            LanguageLocale.getInstance().getLocale());

    //Controller
    private BusquedaProductoController controller;

    /** Creates new form BuscarProductoPnl */
    public pnlBusquedaProducto(GenericFrame frame, boolean modal) {

        //Contructor
        super(frame, modal);

        //Controller
        controller = new BusquedaProductoController();

        //Init components
        initComponents();

        //Init producto components
        initProductosComponents();

        //Set visible
        setTitle(messageBundle.getString("CONTAC.FORM.BUSQUEDAPRODUCTOPNL.TITULO"));
        this.setLocation(400, 300);
        this.setSize(new Dimension(600, 400));
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleHeader = new org.jdesktop.swingx.JXHeader();
        frmBusqueda = new javax.swing.JPanel();
        pnlParametros = new javax.swing.JPanel();
        lblNombreComercial = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblCodigoFabricante = new javax.swing.JLabel();
        txtCodigoFabricante = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new org.jdesktop.swingx.JXTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titleHeader.setBackground(new java.awt.Color(204, 204, 204));
        titleHeader.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        titleHeader.setPreferredSize(new java.awt.Dimension(51, 40));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("contac/commons/components/mensajes/Mensajes_es"); // NOI18N
        titleHeader.setTitle(bundle.getString("CONTAC.FORM.BUSQUEDAPRODUCTOPNL.TITULO")); // NOI18N
        titleHeader.setTitleForeground(new java.awt.Color(255, 153, 0));
        getContentPane().add(titleHeader, java.awt.BorderLayout.NORTH);

        frmBusqueda.setMinimumSize(new java.awt.Dimension(200, 100));
        frmBusqueda.setPreferredSize(new java.awt.Dimension(679, 100));
        frmBusqueda.setLayout(new java.awt.BorderLayout());

        pnlParametros.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblNombreComercial.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNombreComercial.setText(bundle.getString("CONTAC.FORM.BUSQUEDAPRODUCTOPNL.NOMBRE")); // NOI18N

        txtNombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNombre.setToolTipText("");
        txtNombre.setMinimumSize(new java.awt.Dimension(6, 25));
        txtNombre.setPreferredSize(new java.awt.Dimension(59, 30));

        lblCodigoFabricante.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCodigoFabricante.setText(bundle.getString("CONTAC.FORM.BUSQUEDAPRODUCTOPNL.CODIGOFABRICANTE")); // NOI18N

        txtCodigoFabricante.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCodigoFabricante.setToolTipText("");
        txtCodigoFabricante.setMinimumSize(new java.awt.Dimension(6, 25));
        txtCodigoFabricante.setPreferredSize(new java.awt.Dimension(59, 30));

        btnBuscar.setText(bundle.getString("CONTAC.FORM.BTNBUSCAR")); // NOI18N
        java.util.ResourceBundle bundle1 = java.util.ResourceBundle.getBundle("contac/inventarios/app/mensajes/Mensajes_es"); // NOI18N
        btnBuscar.setActionCommand(bundle1.getString("CONTAC.FORM.BTNACEPTAR")); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        txtCodigo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCodigo.setToolTipText("");
        txtCodigo.setMinimumSize(new java.awt.Dimension(6, 25));
        txtCodigo.setPreferredSize(new java.awt.Dimension(59, 30));

        lblCodigo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCodigo.setText(bundle.getString("CONTAC.FORM.BUSQUEDAPRODUCTOPNL.CODIGO")); // NOI18N

        javax.swing.GroupLayout pnlParametrosLayout = new javax.swing.GroupLayout(pnlParametros);
        pnlParametros.setLayout(pnlParametrosLayout);
        pnlParametrosLayout.setHorizontalGroup(
            pnlParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlParametrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNombreComercial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCodigoFabricante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCodigoFabricante, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(241, 241, 241))
        );
        pnlParametrosLayout.setVerticalGroup(
            pnlParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlParametrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreComercial, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodigoFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlParametrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        frmBusqueda.add(pnlParametros, java.awt.BorderLayout.NORTH);

        tblProductos.setEditable(false);
        jScrollPane1.setViewportView(tblProductos);

        frmBusqueda.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(frmBusqueda, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void initProductosComponents() { //<Init components productos>

        //Configurando listado de productos
        productoBeanTableModel = new BeanTableModel<Producto>(Producto.class, controller.getProductos());
        productoBeanTableModel.setModelEditable(false);
        tblProductos.setModel(productoBeanTableModel);
        tblProductos.setRowSelectionAllowed(true);

        //Obteniendo table column model y removiendo columnas innecesarias
        TableColumnModel productoColumnModel = tblProductos.getColumnModel();

        String[] productoColumnRemove = new String[]{"Codigo Barra", "Alias", "Modelo", "Observaciones", "Minimo",
                "Maximo", "Fecha Vencimiento", "Costo CIF", "Costo UND", "Costo FOB", "Costo PROM", "Descuento", "Exento",
                "Precio PROMOCION", "Unidad Medida", "Proveedor", "Clasificador", "Linea", "Estado", "Compuesto",
                "Estatus", "Compania", "Fotografia", "Ctime", "Cuser", "Mtime", "Muser", "Id", "Codigo Cbs", "Marca",
                "Pais Origen",  "Costo DAI", "Costo ISC", "Partida Arancelaria"};

        for (String columnLabel : productoColumnRemove) {
            productoColumnModel.removeColumn(productoColumnModel.getColumn(productoColumnModel.getColumnIndex(columnLabel)));
        }

        //****************************************************
        //Adding cell renderer class to currency price values
        //****************************************************
       /* DecimalFormatRenderer decimalFormatRenderer = new DecimalFormatRenderer();
        decimalFormatRenderer.setHorizontalAlignment(JLabel.RIGHT);
        productoColumnModel.getColumn(2).setCellRenderer(decimalFormatRenderer);
*/
        //****************************************************
        //Ordering table columns
        //****************************************************
        productoColumnModel.moveColumn(1, 0); //Codigo producto


        //Adding listener table productos
        tblProductos.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    //Getting producto selected
                    rowSelected = tblProductos.getSelectedRow();
                    productoSelected = (Producto)((BeanTableModel) tblProductos.getModel()).getRow(rowSelected);

                    //Close JDialog
                    dispose();
                }
            }
        });

    } //<End components productos>

    /**
     * Retorna producto seleccionado
     * @return Producto
     */
    public Producto getProductoSelected() {
        return productoSelected;
    }

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        try {

            //Setting campos de busqueda
            controller.setCodigo(txtCodigo.getText());
            controller.setNombre(txtNombre.getText());
            controller.setCodigoFabricante(txtCodigoFabricante.getText());

            //Buscar productos
            controller.buscarProductos();

            //Renderizar tabla de detalle de productos
            ((BeanTableModel) tblProductos.getModel()).fireTableDataChanged();

        } catch (Exception e) {
            logger.error(e.getMessage(), e);
            JOptionErrorPane.showMessageError(null, e.getMessage(), e.getMessage());
        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JPanel frmBusqueda;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCodigoFabricante;
    private javax.swing.JLabel lblNombreComercial;
    private javax.swing.JPanel pnlParametros;
    private org.jdesktop.swingx.JXTable tblProductos;
    private org.jdesktop.swingx.JXHeader titleHeader;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCodigoFabricante;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    private BeanTableModel<Producto> productoBeanTableModel;
    private Producto productoSelected;
    private int rowSelected;
}
