/**
 * Copyright 2012 Contac Business Software. All rights reserved.
 * CONTAC PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */

/*
 * TasasCambioPnl.java
 *
 * Created on 10-03-2012, 10:54:55 AM
 */
package contac.commons.components;

import contac.commons.app.BusquedaTasasCambioController;
import contac.commons.form.label.JOptionErrorPane;
import contac.commons.form.panel.GenericFrame;
import contac.internationalization.LanguageLocale;
import contac.modelo.entity.TasaCambio;
import org.apache.log4j.Logger;

import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ResourceBundle;

/**
 * @author emortiz
 */
public class TasasCambioPnl extends JDialog {

    //Apache log4j
    private static final Logger logger = Logger.getLogger(AgentesVentasPnl.class);

    //Message resource bundle
    private ResourceBundle messageBundle = ResourceBundle.getBundle("contac/commons/components/mensajes/Mensajes",
            LanguageLocale.getInstance().getLocale());

    //Controller
    private BusquedaTasasCambioController controller;

    /**
     * Creates new form TasasCambioPnl
     */
    public TasasCambioPnl(GenericFrame frame, boolean modal) {

        //Constructor
        super(frame, modal);

        try {

            //Controller
            controller = new BusquedaTasasCambioController();

            //Init components
            initComponents();

            //Init components values
            initComponentsValues();

            //Register listeners
            registerListeners();

            //Set visible
            this.setTitle(messageBundle.getString("CONTAC.FORM.TASASCAMBIOPNL.TITULO"));
            this.setLocation(400, 300);
            this.setSize(new Dimension(200, 300));
            this.setVisible(true);

        } catch (Exception e) {
            logger.error(e.getMessage(), e);
            //Show error message
            JOptionErrorPane.showMessageError(null, messageBundle.getString("CONTAC.FORM.ERROR.INICIO"),
                    e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleHeader = new org.jdesktop.swingx.JXHeader();
        scrollBar = new javax.swing.JScrollPane();
        tasasCambioLst = new javax.swing.JList();

        titleHeader.setBackground(new java.awt.Color(204, 204, 204));
        titleHeader.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        titleHeader.setPreferredSize(new java.awt.Dimension(51, 40));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("contac/commons/components/mensajes/Mensajes_es"); // NOI18N
        titleHeader.setTitle(bundle.getString("CONTAC.FORM.TASASCAMBIOPNL.TITULO")); // NOI18N
        titleHeader.setTitleForeground(new java.awt.Color(255, 153, 0));
        getContentPane().add(titleHeader, java.awt.BorderLayout.PAGE_START);

        scrollBar.setViewportView(tasasCambioLst);

        getContentPane().add(scrollBar, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void initComponentsValues() {

        //Instantiation of ListModel object for JList
        DefaultListModel listModel = new DefaultListModel();
        
        for (TasaCambio tasaCambio : controller.getTasasCambio()) {
            listModel.addElement(tasaCambio);
        }
        
        tasasCambioLst.setModel(listModel);
        tasasCambioLst.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tasasCambioLst.setLayoutOrientation(JList.VERTICAL);
        tasasCambioLst.setVisibleRowCount(-1);

    }

    private void registerListeners() {
        
        this.tasasCambioLst.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    tasaCambioSelected = (TasaCambio)tasasCambioLst.getSelectedValue();

                    //Close JDialog
                    dispose();
                }
            }
        });

        this.tasasCambioLst.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                tasaCambioSelected = (TasaCambio) tasasCambioLst.getSelectedValue();
            }
        });
    }

    public TasaCambio getTasaCambioSelected() {
        return tasaCambioSelected;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollBar;
    private javax.swing.JList tasasCambioLst;
    private org.jdesktop.swingx.JXHeader titleHeader;
    // End of variables declaration//GEN-END:variables

    private TasaCambio tasaCambioSelected;
}
